### PR TITLE
There Is No We in ETC

### PR DESCRIPTION
**Pull request by DonaldMcIntyre**
This is an opinion article based on a conversation we had on the last ETC Community Call.

Soon the Chinese version. It has no video. Only text.

It is for 2023-01-04.

### CODE REVIEW

**Comment by TheCrowbill** [comment]
> This is an opinion article based on a conversation we had on the last ETC Community Call.

@DonaldMcIntyre, are you suggesting this article should be tagged as "Opinionated Content" when published on the website?  If so, shouldn't that be part of this pull request?

**Review by gitr0n1n — DISMISSED** [review]
LGTM. It might make sense to add a clear h2 header that this is an Opinion piece. I do see you classified it as opinion in the metadata. @DonaldMcIntyre 

example of header markup:
```
## Opinion Article
```

**Comment by w1g0** [comment]
The protocol doesn't care about opinions and follows "Code Is Law" to protect its principles. When we move up to the layer 2 (and up) there are communities being formed and therefore I don't agree with the title, there is "we" in ETC as a subset.

**Comment by gitr0n1n** [comment]
> The protocol doesn't care about opinions and follows "Code Is Law" to protect its principles. When we move up to the layer 2 (and up) there are communities being formed and therefore I don't agree with the title, there is "we" in ETC as a subset.

One the actual content added in this PR-
I think you bring up good points here @w1g0 . Of course there is a "We" because otherwise "we" wouldn't have resisted the ETH Foundation, "we" wouldn't have collectively thought of ways to solve the 51% attack threat, replay threat, difficulty bomb threat, monetary policy uncertainty, ossification to the ethash-family of algorithm and associated hardware, rejection of protocol level treasuries....this was all done by an open and inclusive "we" against a centralizing "them".

Of course there is an ETC Community
- protocol level contributors
- client level contributors
- mining level contributors
- development contributors
- end users

So @DonaldMcIntyre maybe there is a way to reframe this rather than there is "no we" it is more, "we" is open and decentralized with the guiding principles that prevent actors from pushing through centralization/control. Just as Bitcoin has a "we". Examples: "Small Blockers vs. Big Blockers". This is also a time to highlight that Hard Forks are a feature. If a centralized actor attempts to push a centralizing update- the users are free to do nothing and hard fork away from that upgrade- this ties into the ETC origin story when ETH forked away from ETC in a centralizing manner.

Lastly on this note, I'm going to pull my approval so we can have the conversation on Opinion pieces on the site that aren't hosted at a third-party site like the "ethereumclassicclassic" note. I'm not sure if we have had that convo. But likely worth clarification.

**Comment by DonaldMcIntyre** [comment]
@w1g0 @gitr0n1n I think it's a waste of time to try to convince you that there is no "we" in a decentralized blockchain and why believing in "we" is actually a security hole. I will pull out this article from the community website and post it on Etherplan. 

I had already marked it as "opinion" and that should add the tag on the top.

Now we have a whole in this week's publishing schedule 🤦‍♂️.

**Comment by gitr0n1n** [comment]
> I will pull out this article from the community website and post it on Etherplan.
> 
> Now we have a hole in this week's publishing schedule 🤦‍♂️.

Sounds like a good solution. I'll check for the PR for that external article's link tomorrow.

**Pull request closed without merging**
