### PR TITLE
add nusd

### PR DESCRIPTION
**Pull request by paulobaronceli**

### CODE REVIEW

**Comment by IstoraMandiri** [comment]
Looks good but you need to make sure the image is uploaded in your repo and linked locally.

So it should be`image: ./images/nusd.jpg`, with `nusd.jpg` being the image you upload in the relative directory.

**Comment by paulobaronceli** [comment]
> Looks good but as [mentioned](https://github.com/ethereumclassic/ethereumclassic.github.io/pull/847#issuecomment-1229346932) you need to make sure the image is uploaded in your repo and linked locally.
> 
> So it should be`image: ./images/nusd.jpg`, with `nusd.jpg` being the [image](https://raw.githubusercontent.com/nova-network-inc/common-assets/main/token-info/0xab1E9D7551c1B161cedf96AeaC66b95bc5cCd7d4/logo.png) you upload in the relative directory.
> 
> This website builds everything from local source files those images need to be in the repo.

Just submitted the logos with another PR and updated the path. Will do the same with Fusion, thanks!

**Review by w1g0 — APPROVED** [review]

**Comment by w1g0** [comment]
> > Looks good but as [mentioned](https://github.com/ethereumclassic/ethereumclassic.github.io/pull/847#issuecomment-1229346932) you need to make sure the image is uploaded in your repo and linked locally.
> > So it should be`image: ./images/nusd.jpg`, with `nusd.jpg` being the [image](https://raw.githubusercontent.com/nova-network-inc/common-assets/main/token-info/0xab1E9D7551c1B161cedf96AeaC66b95bc5cCd7d4/logo.png) you upload in the relative directory.
> > This website builds everything from local source files those images need to be in the repo.
> 
> Just submitted the logos with another PR and updated the path. Will do the same with Fusion, thanks!

Isn't it leaner to edit the logos on the current PR's for fusion and nUSD?

**Comment by IstoraMandiri** [comment]
I can see why the github UI might make things annoying to upload as part of this PR so I've approve #859 for the sake of expedience, once that is merged then these can be approved as long as it builds properly.

**Review by brolal — APPROVED** [review]

**Pull request merged**
