### PR TITLE
Add COC, License & Netlify footer to apply for Netlify hosting

### PR DESCRIPTION
**Pull request by hitchcott**
This PR meets the requirements of https://www.netlify.com/legal/open-source-policy/ for #488 

If this PR is merged, we can then apply for free netlify teams hosting, which will further decentralize the project by allowing a number of users (rather than just myself) to control the netlify hosting.

Please discuss and confirm whether the license and other choices here are agreeable!

### CODE REVIEW

**Comment by gitr0n1n** [comment]
Great news @hitchcott ! So happy you had some bandwidth to work out this PR!

**Review by gitr0n1n — APPROVED** [review]
LGTM!

**Review by TheEnthusiasticAs — APPROVED** [review]

**Comment by TheEnthusiasticAs** [comment]
lgtm too. Lets merge it at the end of this week and give the participants time think about

**Review by kimisan — APPROVED** [review]

**Comment by TheEnthusiasticAs** [comment]
ok, it seems the ETC participants accepted it. I am merging and closing it

**Pull request merged**
