### PR TITLE
Add to MetaMask button, fixes #811

### LINKED ISSUE #811: Button to auto-config Metamask
Simple as: 
```
const params = [{
    chainId: '0x3d',
    chainName: 'Ethereum Classic',
    nativeCurrency: {
      name: 'ETC',
      symbol: 'ETC',
      decimals: 18
    },
    rpcUrls: ['https://www.ethercluster.com/etc'],
    blockExplorerUrls: ['https://blockscout.com/etc/mainnet/']
  }]

const args = { 
  method: 'wallet_addEthereumChain', 
  params: params
}
window.ethereum.request(args)
```

### PR DESCRIPTION
**Pull request by IstoraMandiri**
This PR adds a button to the footer that allows user to add to metamask.

It also updates donald's article to include the button at the top of the page.

**Important:** Before merging, please can we check all the details are correct and it works in various environments? I have not been able to test extensively.

EDIT: It appears that if Network ID 61 is already added then it will silently fail. I may need to add some additional logic to deal with this confusion, but for most newcomers they should see a popup in metamask. If you delete your existing ETC network (and refresh) then you should see it pop up again.

### CODE REVIEW

**Review by gitr0n1n — APPROVED** [review]
Working for me.

**Comment by justjinn** [comment]
Attempted metamask button, got message: 

The page at https://deploy-preview-184-ethereumclassic...

Metamask not detected.

**Comment by justjinn** [comment]
That message may be due to me not going through the metamask extension. I am on my phone.

**Comment by justjinn** [comment]
Attempted again, through my phone and opened with metamask app - not working for me. Metamask browser opens through netlify. No pop up - but haven't tried deleting my ETC link and starting new. "+ ETC to MetaMask" not working for me.

**Review by w1g0 — COMMENTED** [review]
The buttons are visible but when I click on it, nothing happens...
https://deploy-preview-814--ethereumclassic.netlify.app/guides/metamask

**Comment by IstoraMandiri** [comment]
I think instead of a script, we should just link to https://chainlist.org/en/chain/61

**Review by gitr0n1n — APPROVED** [review]
Seems like a good solution @IstoraMandiri

**Review by w1g0 — APPROVED** [review]

**Pull request merged**
