### PR TITLE
Add ETCPunks

### PR DESCRIPTION
**Pull request by beatercode**
Adding ETCPunks NTF ETH Classic projct to blog

### CODE REVIEW

**Review by gitr0n1n — CHANGES_REQUESTED** [review]
Can you change this to a third party article and add it that way. the Blog is typically for ECIP and other protocol news. You're welcome to add your ETC Punks project to the news feed via adding a link to a third party article.

https://ethereumclassic.org/news

Also please add your product to this page:
https://ethereumclassic.org/ecosystem/apps-and-protocols

**Review by hitchcott — APPROVED** [review]

**Comment by hitchcott** [comment]
LGTM, prefer this over #664

**Comment by beatercode** [comment]
Any news ?

**Comment by beatercode** [comment]
Could you accept the changes?

**Review by TheEnthusiasticAs — APPROVED** [review]

**Comment by TheEnthusiasticAs** [comment]
done @beatercode. Thx

**Pull request merged**
