### PR TITLE
Update post content for Mystique with more information

### PR DESCRIPTION
**Pull request by ziogaschr**
The source of the content is from https://etccooperative.org/posts/2021-01-27-mystique-hard-fork

### CODE REVIEW

**Comment by bobsummerwill** [comment]
I do not have review rights, but LGTM.

Do you have a list of people with review rights, @gitr0n1n or @IstoraMandiri?

**Review by bobsummerwill — APPROVED** [review]

**Comment by gitr0n1n** [comment]
> I do not have review rights, but LGTM.
> 
> Do you have a list of people with review rights, @gitr0n1n or @IstoraMandiri?

Does this mean you have review rights now @bobsummerwill ? I don't have a recent list of reviewers- we should likely put that somewhere in the repo for proper assignemnts. Good note Bob! cc: @IstoraMandiri

**Comment by IstoraMandiri** [comment]
@bobsummerwill pretty sure you have review rights

**Comment by bobsummerwill** [comment]
Looks like I did when *explicitly* added as a reviewer.  So I imagine that is the case for anybody.

But I don't have any elevated privileges.

**Pull request merged**
