### PR TITLE
Removing Inactive Projects

### PR DESCRIPTION
**Pull request by cosmosquark**
As mentioned on discord.

All of these URLs have been down for a while

https://dappdirect.net/ 
https://luckygames.io/ 
https://onex.network/ 
http://arena.highlander.network/  
https://etcodyssey.com/

### CODE REVIEW

**Review by w1g0 — APPROVED** [review]

**Review by w1g0 — COMMENTED** [review]
All three websites are up, so I can't approve these changes.

**Comment by cosmosquark** [comment]
@w1g0 will keep things within scope of websites that are obviously down :+1:

**Comment by w1g0** [comment]
@cosmosquark it is very possible that the suggestions were right but I'm not aware of the rationale with what they were placed in the first place and if they are still valid. If I'm not mistaken it was approved by @hitchcott, @gitr0n1n and @TheEnthusiasticAs.

**Comment by cosmosquark** [comment]
I have reverted to the state just to include sites that are obviously down.

**Review by TheEnthusiasticAs — APPROVED** [review]

**Comment by TheEnthusiasticAs** [comment]
@cosmosquark thx for the PR. Please, labele the PRs next time

**Comment by TheEnthusiasticAs** [comment]
> @cosmosquark it is very possible that the suggestions were right but I'm not aware of the rationale with what they were placed in the first place and if they are still valid. If I'm not mistaken it was approved by @hitchcott, @gitr0n1n and @TheEnthusiasticAs.

Everyone can contribute. If you see an invalid link, then it correct to report here

**Pull request merged**
