### PR TITLE
How to Keep Your ETC Secure

### PR DESCRIPTION
**Pull request by DonaldMcIntyre**
This is a guide of how to keep your ETC secure. It is related to the previous post about how ETC is so valuable during banking crises. It's like a continuation because it explains the paradigm change and how to keep your stuff secure. 

"How to Keep Your ETC Secure"

EN

CN version coming done.

It will be published on 2023-04-12. We have a 14 day lead.

### CODE REVIEW

**Review by gitr0n1n — APPROVED** [review]

**Comment by bobsummerwill** [comment]
FYI ... @gitr0n1n ... you have been tagging me for reviews a few times recently.

I am reclusing myself from reviews of Donald's content on ethereumclassic.org in general.
I don't want us to be "forcing" Coop-generated content through the pipeline.
In general none of this educational material is URGENT.

**Comment by bobsummerwill** [comment]
@IstoraMandiri  - no, there were multiple individual taggings as well.

"You leave the https://github.com/orgs/ethereumclassic/teams/website group and we add you as an individual contributor so you don't get pinged by this group (not ideal for user management / security)" - yes, please.   It does not make sense for me to be in that group anymore, I don't think.

Also, I don't think it is necessary to tag the group either.   Anybody can choose to Watch the repo anyway, and will get the same emails.   But whatever works - I just don't need to be in the loop on any of this stuff unless my input is specifically required for something.

**Comment by gitr0n1n** [comment]
> @IstoraMandiri - no, there were multiple individual taggings as well.
> 
> "You leave the https://github.com/orgs/ethereumclassic/teams/website group and we add you as an individual contributor so you don't get pinged by this group (not ideal for user management / security)" - yes, please. It does not make sense for me to be in that group anymore, I don't think.
> 
> Also, I don't think it is necessary to tag the group either. Anybody can choose to Watch the repo anyway, and will get the same emails. But whatever works - I just don't need to be in the loop on any of this stuff unless my input is specifically required for something.

Nah @bobsummerwill , I haven't been tagging you directly. I've been tagging the teams for the website and the tweeter groupings, usually after I respond to a ping (since two reviews are required). You can go back and review who tagged you in the PRs or manage your notifications locally. Cheers.

image

**Comment by gitr0n1n** [comment]
> @bobsummerwill roger that, removed at your request.
> 
> > Removing members from the Website team will also delete their forks of any private Website-owned repositories. This may take up to 24 hours to occur.
> 
> I'll leave it up to @ethereumclassic/website to discuss future tagging etiquette. Perhaps it's better that we only request reviews specifically from individuals if their input is relevant to the PR.

I think the approach of removing Bob is the correct one. Alternatively he could mute his notifications if he does not intend to participate, but then why be added to groups?

I think the team tagging etiquette is working as intended after the change to that with the Twitter-Together integration. It has been a welcomed change from the older direct pings I used to get, as there are many PRs that are approved before I review. It looks like Donald isn't getting slowed down from posting his content like when many of us were on holiday around the new year. Cheers.

**Comment by TheCrowbill** [comment]
> I'll leave it up to @ethereumclassic/website to discuss future tagging etiquette. Perhaps it's better that we only request reviews specifically from individuals if their input is relevant to the PR.

I have no problems with the number or frequency of pings I'm receiving, whether direct to me or by way of tagging the team.

If Bob is experiencing a ping overload, I can understand him seeking relief. However, the value I see in keeping review requests sent to the website team is that it removes any appearance of a content creator "cherry-picking" reviewers.

If my review will be of any help, ping away. ;-)

**Pull request merged**
