### PR TITLE
Contribute to ETC: Community Tweets

### PR DESCRIPTION
**Pull request by DonaldMcIntyre**
This is a post of the series "How to Contribute to ETC". This one is about the Twitter Together system.

Chinese version added.

This one will be published on 2023-02-14.

### CODE REVIEW

**Comment by TheCrowbill** [comment]
@DonaldMcIntyre @IstoraMandiri should the option of using the `#ETCTweets` hashtag for Tweet proposal be included in this article for those who have no GitHub?

**Review by TheCrowbill — CHANGES_REQUESTED** [review]
Please see my previous comment concerning some additional content.

**Comment by DonaldMcIntyre** [comment]
> @DonaldMcIntyre @IstoraMandiri should the option of using the `#ETCTweets` hashtag for Tweet proposal be included in this article for those who have no GitHub?

I didn't see this included in the GitHub instructions. I am going to write a separate tutorial and short video describing the #ETCTweets hashtag. I would leave this one isolated with the GitHub instructions for those who have GitHub.

**Review by TheCrowbill — APPROVED** [review]
LGTM

**Review by brolal — APPROVED** [review]

**Pull request merged**
