### PR TITLE
Revert "ETC Ecosystem Spotlight: HebeSwap Part I"

### PR DESCRIPTION
**Pull request by gitr0n1n**
Reverts ethereumclassic/ethereumclassic.github.io#1252

@DonaldMcIntyre pushed through without addressing requested changes.

### CODE REVIEW

**Comment by DonaldMcIntyre** [comment]
It was not necessary to address any changes because the PR had the required approvals after sufficient debate and the admin requesting changes has a conflict of interest with the underlying subject.

**Comment by DonaldMcIntyre** [comment]
Closing due to disruptive behavior by the admin.

**Comment by gitr0n1n** [comment]
> It was not necessary to address any changes because the PR had the required approvals after sufficient debate and the admin requesting changes has a conflict of interest with the underlying subject.

The author of the document attacked two independent reviewers that were addressing the drastic change this blog post has regarding promotional material compared to every other blog post. The author, @DonaldMcIntyre closed and opened multiple PRs, then rushed his PR through approval without addressing the requested changes. Most of which was in relation to accuracy of the article.

Now the author is closing and suppressing any discussion on the addition of the promotional material he is submitting to the project's main RSS feed to promote a private dapp project he likes. Please refrain from abusing your permissions @DonaldMcIntyre. you've submitted a blog that is not like any other blog submitted to date.

**Comment by gitr0n1n** [comment]
@ethereumclassic/website can we get control of @DonaldMcIntyre not following common procedure we have used on this platform for many years now.

**Comment by TheCrowbill** [comment]
@DonaldMcIntyre and @gitr0n1n, I am calling you both out for what I see as unprofessional behavior. You two are each using GitHub tricks and technicalities to stifle each other's attempts to direct the way this issue is decided by silencing the opposing view. That is unacceptable to me. If we can't discuss and debate our position on issues of relevance such as this while maintaining professional decorum,  I fear for the future of this community.

Please leave name-calling and finger-pointing off this public venue. And please stop using a tactic of any kind to steamroll an ongoing policy discussion.  Be involved. Be adamant. But personal attacks and intentional sidesteps of the opposing view crosses a line.

**Comment by DonaldMcIntyre** [comment]
The reason why it should be reverted is not because it is shared or it would break links, it is because it was approved and the objections of the objector admin are solely because he has a competing project and is jealous that his was not covered. 

Please stop this charade and stop indulging Ronin and his perverse behavior. He should be out of anything related with ETC community assets.

Open your eyes.

**Comment by DonaldMcIntyre** [comment]
> Update from discord:
> 
> 
> 
> image
> 
> 

Do it. I did not know how submitted you were to Ronin.

**Comment by gitr0n1n** [comment]
promotion: the publicization of a product, organization, or venture so as to increase sales or public awareness.
"a sales promotion company"

Again, all dapps, tokens, wallets, services may start to use this RSS feed to promote their products/services due to Donald's contributions (if we are not giving ETC Coop and Hebe preferential treatment). Donald would make it seem like I will be upset about it, this personally benefits our products, but is a drastic change from the website prior to his contributions. Now all these products may use this process to submit promotional content:
https://ethereumclassic.org/services/apps
https://ethereumclassic.org/services/wallets
https://ethereumclassic.org/services/exchanges

**Review by TheCrowbill — APPROVED** [review]
This merge illustrates the technicalities I pointed out in an earlier comment on this PR. While technically meeting the review requirements of approval for merging, it is evident that there was a  rush to **merge as a weapon** by one of the militants in yesterday's war of discussion suppression.

With the obvious contention surrounding PR #1252, merging should have waited despite the two approving reviews.

**Comment by TheCrowbill** [comment]
> @gitr0n1n if you have no contention, please close this in favor of #1263 and #1260

With the merge of #1263 this revert PR is no longer appropriate.

Discussion is apparently now ended with no contention to closing voiced by @gitr0n1n 

Closing.

**Pull request closed without merging**
