### PR TITLE
Merge "Update disclosure about relationship between Bob and Alison" from staging

### PR DESCRIPTION
**Pull request by bobsummerwill**
"Update disclosure about relationship between Bob and Alison"
https://github.com/ethereumclassic/ethereumclassic.github.io/pull/236

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Why on earth are these diffs so noisy?
121 files changed for one line of text?
I would expect us to have diff for the source file and a diff for a generated HTML file.

I wonder if we have something misconfigured, @hitchcott?

As it stands, these code reviews are pretty useless in themselves.   Yes, we can point to the PR for the source change, as I did here, but really you want the generated file diff here to be reviewable too.

**Comment by hitchcott** [comment]
Hi Bob,

This diffing is due to: https://www.gatsbyjs.org/docs/how-code-splitting-works/

Gatsby generates each page with links different data chunks, named with their content hash (for cache busting); so by default, if you change the content of one page, it will update the list of content hashes on every page.

I'm going to install https://www.gatsbyjs.org/packages/gatsby-plugin-remove-fingerprints/ to see if this fixes this and makes this diff easier to read.

**Comment by hitchcott** [comment]
I'm now led to believe the issue was a subtle caching bug on travis' end. It's now not doing this (see latest pushes to source).

See the recent rebuilds; they do not change all the files.

(Test to change a single file)
https://github.com/ethereumclassic/ethereumclassic.github.io/pull/237/commits/8916dd05e3bcaf5143d186b69c67fa5e510199f7

(Reset that file to previous commit)
https://github.com/ethereumclassic/ethereumclassic.github.io/pull/237/commits/d0b4278fabfd4fcd46f613b5267e26b0a2b9bb9d

If this happens again I'll investigate further.

**Comment by bobsummerwill** [comment]
Cool.

Well I will make some more PRs, and we will see how noisy the outputs are.

**Comment by hitchcott** [comment]
Seems like this is still an issue. 

Tracking upstream here: https://github.com/gatsbyjs/gatsby/issues/12066#issuecomment-562834121

For now I don't want to mess with the cache busting as it might cause things to not cache-bust. We might need to live with noisy builds temporarily.

**Comment by bobsummerwill** [comment]
Thanks for the update.  We will just to keep an eye on this and do what we can.

**Pull request merged**
