### PR TITLE
Fix search results

### PR DESCRIPTION
**Pull request by IstoraMandiri**
Last PR caused a bug in search only testable in production, please approve PR to attempt to fix.

@ethereumclassic/website

### CODE REVIEW

**Review by TheCrowbill — DISMISSED** [review]
Approving as requested, but I did not verify each changed line of code.

**Comment by IstoraMandiri** [comment]
I pushed to this branch again, which resets old reviews.

**Review by TheCrowbill — APPROVED** [review]
lgtm

**Comment by TheCrowbill** [comment]
Tested search on website and all is working as expected, so far.

**Pull request merged**
