### PR TITLE
Adds promotional disclaimer for Spotlight articles

### PR DESCRIPTION
**Pull request by TheCrowbill**
This PR is intended to provide an additional option regarding the publication of articles and material that could be considered as promoting a particular product, service, or entity.

Currently, there are apparently only two options available to maintainers: 1) approve whatever @DonaldMcIntyre  submits without modification,  or 2) block whatever submissions @gitr0n1n does not want to be introduced This is an attempt to create a path to publication for information that many would find valuable while maintaining the neutrality of the publisher (this website).

Added is a disclaimer on the article header similar to that already in use for Opinionated Content. 

This PR also applies the disclaimer option to the Spotlight article on HebeBlock which is already merged.

### CODE REVIEW

**Review by gitr0n1n — APPROVED** [review]
great compromise to a blog post that contained promotional content never approved on this website before.

**Comment by gitr0n1n** [comment]
ronin — Today at 1:25 PM
Donald, you literally suppressed the conversation. Teams in the past have tried to submit promotional content like this and had it rejected. How do you claim bias? when its literally always been the precedent. But now because you submit a blog post, and bully people while throwing a fit opening and closing PRs, it gets approved?

This has been a line we never crossed for years, but now...its been force merged without discussion.
As mentioned, this now enables me to use the RSS feed of the project as a marketing tool. So its a personal benefit for me. But it was contrary to how the website has been used in the past.

As @TheCrowbill mentioned- if its the Hebe and ETC Coop teams- special treatment is applied that everyone else on this network does not get. Did I set the precedent to not post promotional content on the RSS feed- no. The envelope was pushed. Does it benefit me personally- yes. But do I think it will be to the detriment to the website in the long-run- yes.

**Comment by gitr0n1n** [comment]
Now he is closing PRs that would be promotional like his article. This was draft to show how the website now changes. Every single team deploying on ETC can now submit PRs to have their product featured in the RSS feed.

https://github.com/ethereumclassic/ethereumclassic.github.io/pull/1257

All of these products can now draft articles for publicity like Donald is doing for this product he views special.
https://ethereumclassic.org/services/apps

**Comment by DonaldMcIntyre** [comment]
This shows that you continue to miss the point. The only issue here is that there is an admin in this organization, and he is an editor in the ECIP process which is even worse, who has historically repeatedly disrupted normal processes in ETC, and who has conflicts of interests in this case in particular so he decided to disrupt the publication of the post because he finds it offensive that his competition is being covered and not his team and dapps. Nothing more.

Everything else that he is arguing is gaslighting and manipulation that does need to be addressed. They are all non-issues that he created and you fall for his con disrupting the process as well and introducing unnecessary and bureaucratic hurdles.

ETC is a very small project with a very small group of people trying to make it barely survive. To introduce these grand rules as a consequence of the silly behavior of one admin is not conducive of any solution nor improvement to the process.

I have removed myself from the https://github.com/ethereumclassic organization and will reduce my participation to only pushing PRs following my usual schedule. You may d whatever you wish with them. 

I will not spend more time trying to promote any of the posts nor calling your attention to approve them. As always, you can reject and delete whatever I propose.

I suggest you remove @gitr0n1n from this repo, he has always been and will always be bad news. 

@gitr0n1n, I will not cover nor write about your products. You, your team, and dapps have proven to be a completely untrustworthy. This poses a risk to my readers.

**Comment by gitr0n1n** [comment]
> being covered and not his team and dapps. Nothing more.

You understand I can draft the exact same content for any product I deploy right? This is an illogical point of view by yourself.

**Comment by gitr0n1n** [comment]
> I have removed myself from the https://github.com/ethereumclassic organization and will reduce my participation to only pushing PRs following my usual schedule. You may do whatever you wish with them.

I think this is wise, since you are the ONLY person in this entire conversation that has overstepped their roles and suppressed conversation by Dismissing/Opening PRs/Closing PRs. You have no once addressed that the content your submitting is in line with other previous content that was rejected due to be promotional in nature.

I get that you're upset, but you throwing fits and bullying doesn't have the desired affect on me. You called for my removal when ETC Coop violated the ECIP process and was prevented from rush merging ECIP-1049 to Accepted status in 2020. You called for my removal when I held the meeting that removed ECIP-1049 for being dated and stale (which were the reasons Bob withdrew it a few weeks later). And you've called for my removal now because you want to use the project's website to promote a private project you like and *may* have a financial interest in. Maybe it is you, my friend, that has the bias as an ECIP-1049 proponent and promoter of this private project.

**Review by gitr0n1n — APPROVED** [review]
If we are going to have promotional content now. I feel its important to label it clearly on the website since the RSS will now be open to adverts. This opens the flood gates for many projects in the future. Some of them will 100% be scams and rug pull the ETC users.

**Comment by TheCrowbill** [comment]
> Language wise, I'm not keen, the site shouldn't be "promoting" anything IMO, so I propose:
> 
> * Instead of "promotion" we should name something like "Third Party", with warnings similar to those we have in Apps section.

To be clear, I am not in favor of having promotional content on this website at all. Despite @DonaldMcIntyre's claims of having submitted multiple product reviews which we have published in the past, the fact is that until #1252 never has there been a product or team review on this or previous iterations of ethereumclassic.org. What he is calling "reviews" are in fact walkthroughs or guides. These are useful, necessary, and practical information pieces appropriate for publication here.

> * Make minor edit the Hebeswap article to make sure it is not perceived as promoting (ensure neutral tone)

It is my experience that @DonaldMcIntyre is resistant to editorial review. He resists all editorial changes to his articles, even those correcting blatant grammatical errors. I doubt there will be much cooperation forthcoming on #1252 or any of his future submissions. Regarding edits to this particular article, by DM to me this morning he said, _"The article is perfect and has no bias nor anything that is not standard in the website."_

> * Resolve [ETC Ecosystem Spotlight: HebeSwap Part I #1252 (review)](https://github.com/ethereumclassic/ethereumclassic.github.io/pull/1252#pullrequestreview-1486607870)
> 
> I made #1260 as an alternative/complementary approach.

PR #1259 is not my preference, but if we **must** introduce "advertorials" to the website then this disclaimer or one with similar yet equivalent wording should be standard policy.

**Comment by TheCrowbill** [comment]
Withdrawn in favor of #1263

**Pull request closed without merging**
