### PR TITLE
Update Deps, Content Updates, Fixes

### PR DESCRIPTION
**Pull request by IstoraMandiri**
Resolves  a number of content related outstanding issues

### CODE REVIEW

**Review by w1g0 — DISMISSED** [review]

**Review by TheCrowbill — APPROVED** [review]
Lots of changes! I was unable to view the changes to `package-lock.json` in GitHub. I did, however, clone the repo to GitHub Desktop to check the preview.

LGTM

**Comment by TheCrowbill** [comment]
Aware that I don't have write access, but its good practice. I'm finding myself a bit rusty.

**Review by w1g0 — APPROVED** [review]

**Review by brolal — APPROVED** [review]

**Comment by w1g0** [comment]
@IstoraMandiri, it seems there's something wrong with the rights. @brolal's checkmark and mine isn't green so merging is blocked.

**Comment by IstoraMandiri** [comment]
@w1g0 I mentioned this in #website discord. A remedy is on the way.

**Pull request merged**
