### PR TITLE
Add in Nifty Wallet and Dappdirect.net

### PR DESCRIPTION
**Pull request by antsankov**

### CODE REVIEW

**Comment by hitchcott** [comment]
Do we want to put this in the knowledge base, or in the ecosystem section?

Dappdirect is already in the ecosystem.

Maybe we put a link to the ecosystem from the knowledge base.

**Comment by bobsummerwill** [comment]
So I think we should NOT list Nifty Wallet specifically.

Because we not listing any wallet, exchanges, etc as then it becomes a game of "getting blessed" again.

And DappDirect is already listed.

I think?

**Comment by hitchcott** [comment]
Reason behind "not listing Nifty Wallet specifically"?

**Comment by bobsummerwill** [comment]
I suppose for consistency it should be added.
For consistency we should add all the entries from etcnodes.org list.

We need to list nothing or everything.   My preference at the time we started the site reboot was that we not list anything “ETC available at all good stores” but during Agharta we ended up doing all the work anyway, so I guess we might as well just list everything.

**Comment by TheEnthusiasticAs** [comment]
Agree with Bob. But the warning above it should still stay on the etc website.

**Comment by hitchcott** [comment]
All of the clients are now clearly listed no the develpoment branch @bobsummerwill 

https://develop--ethereumclassic.netlify.com/ecosystem/

I've included Nifty Wallet under web wallets.

Hopefully we can get MetaMask on here someday!

**Pull request closed without merging**
