### PR TITLE
Roadmap Update - OpenETC was deleted from Roadmap due to unexpected project drop & also see #542

### PR DESCRIPTION
**Pull request by TheEnthusiasticAs**
but it remains in the timeline without the link

### CODE REVIEW

**Comment by gitr0n1n** [comment]
Can you remove this OpenETC project launch, since it appears the project wont be developed due to the bugs in OE? If the project gets some legs we can add it back in. It seems all hashrate is moving away from ParityEthereum and the branches OETH and OETC.

Also can you add the 51% Attack if you're updating the timeline?

**Comment by kimisan** [comment]
> Can you remove this OpenETC project launch, since it appears the project wont be developed due to the bugs in OE? If the project gets some legs we can add it back in. It seems all hashrate is moving away from ParityEthereum and the branches OETH and OETC.
> 
> Also can you add the 51% Attack if you're updating the timeline? @TheEnthusiasticAs

OpenETC Project creator(Jongchan Jang) is also be related to $ASUKA scam exit.

**Comment by ondertitels** [comment]
Please remove everything related to Openetc and Asuka on the website he’s a scammer.

**Comment by TheEnthusiasticAs** [comment]
@gitr0n1n @kimisan @ondertitels I removed completely the OpenETC on the roadmap page and added the second network reorg event on the timeline. Thanks!

**Pull request merged**
