### PR TITLE
public-request

### PR DESCRIPTION
**Pull request by gitr0n1n**
twitter

### CODE REVIEW

**Comment by IstoraMandiri** [comment]
I support the sentiment, but I think it would be ideal to be as neutral as possible with the language, and/or make it super clear with a disclaimer who is authoring this.

E.g. Remove "Misinformation" claim

Perhaps also add a short intro paragraph about the situation in a neutral way. Something like:

> An ongoing discussion regarding control of the verified eth_classic twitter account has been recently brought to the forefront. The account has been owned by IOHK since 2016 and operated by various ETC community members. After IOHK ceased contributions to ETC following the rejection of Treasury Proposal ECIP-1098, many hoped that they would hand over control of the account to active ETC contributors. Recently CEO of Charles Hoskinson has made statements claiming they do not intend to do this.

**Review by w1g0 — COMMENTED** [review]
On line 17 I would add quotes for better readability, great write up! 👏
In an effort to be proactive in resolving this issue, the Ethereum Classic community has setup a “Twitter, Together!” repository to manage the Ethereum Classic project's twitter account at [https://github.com/ethereumclassic/twitter-together](https://github.com/ethereumclassic/twitter-together).

**Review by w1g0 — APPROVED** [review]

**Comment by w1g0** [comment]
> I support the sentiment, but I think it would be ideal to be as neutral as possible with the language, and/or make it super clear with a disclaimer who is authoring this.
> 
> E.g. Remove "Misinformation" claim
> 
> Perhaps also add a short intro paragraph about the situation in a neutral way. Something like:
> 
> > An ongoing discussion regarding control of the verified eth_classic twitter account has been recently brought to the forefront. The account has been owned by IOHK since 2016 and operated by various ETC community members. After IOHK ceased contributions to ETC following the rejection of Treasury Proposal ECIP-1098, many hoped that they would hand over control of the account to active ETC contributors. Recently CEO of IOHK Charles Hoskinson has made statements claiming they have no intention to do this.

Stating that they have no intention to do so is an insinuation, they don't reply on the subject which was asked by @bobsummerwill many times. Maybe they focus on other subjects or they deliberately ignore, I won't be the judge.
The outcome should be that the community gets informed on a regular basis by people that have the best intention for ETC with its principles. Doing that with the “Twitter, together” repository sounds like the best way forward and is definitely worth a try and without a doubt a better situation than the deadlock it's in now.

**Review by w1g0 — COMMENTED** [review]
Scratch that, he just tweeted https://twitter.com/IOHK_Charles/status/1566911099630387205
It was deliberate...

**Comment by gitr0n1n** [comment]
Closing. I don't feel this is the appropriate approach yet. Maybe after we have organized Twitter Together.

**Comment by bobsummerwill** [comment]
I think that is the right call, @gitr0n1n.

Just too whiny and weak.

**Comment by bobsummerwill** [comment]
Instead we build.

**Pull request closed without merging**
