### PR TITLE
Update Exchange Section of Website to 2022 Markets

### PR DESCRIPTION
**Pull request by gitr0n1n**
+ Added Derivatives Section (Perps and Futures)
+ Update Exchanges List to 2022
+ Removed Dead Links
+ Moved trust minimized to the top. Included non-chain native trust minimized products that support ETC.
+ rename "Instant" to "Cross-Chain Exchanges" to better describe these swapping products.

### CODE REVIEW

**Review by IstoraMandiri — APPROVED** [review]
I haven't checked every link but nothing looks out of whack here

**Review by Jamyye — APPROVED** [review]
Reviewed and approved

**Review by IstoraMandiri — APPROVED** [review]
In light of #925 I will retract this approval until I have checked all these links

**Review by IstoraMandiri — CHANGES_REQUESTED** [review]
Not sure how to cancel a review so I'lll request changes for now

**Comment by gitr0n1n** [comment]
Updated the Title to be very clear.
Updated the Bullet list to be very clear.

**Comment by gitr0n1n** [comment]
> Not sure how to cancel a review so I'lll request changes for now

Yes, title, description and actions have been clearly documented on the bullets to reflex all commits through this clean up. Should be goof for detailed review now after @w1g0 feedback.

**Review by Jamyye — APPROVED** [review]
Looks good to me 👍

**Review by IstoraMandiri — APPROVED** [review]

**Comment by IstoraMandiri** [comment]
LGTM @w1g0 @brolal

**Review by w1g0 — DISMISSED** [review]
line 26 trust minimizing -> trust minimized

**Review by justjinn — APPROVED** [review]

**Pull request merged**
