### PR TITLE
Backtag articles

### PR DESCRIPTION
**Pull request by gitr0n1n**
BackTag 2020 Articles

More to come

### CODE REVIEW

**Comment by hitchcott** [comment]
fixed here: https://github.com/gitr0n1n/ethereumclassic.github.io/pull/10

**Comment by gitr0n1n** [comment]
errors. need to redo, easier to scrap

**Comment by hitchcott** [comment]
Cool, working now. Does it look good to you @gitr0n1n ?

**Comment by hitchcott** [comment]
There appears to be some typos 

image

**Comment by gitr0n1n** [comment]
Should be good now @hitchcott

**Comment by hitchcott** [comment]
Awesome, thank you @gitr0n1n !

**Pull request merged**
