### PR TITLE
Video: Blockchain Course Part 1

### PR DESCRIPTION
**Pull request by gitr0n1n**
Blockchain Course Part 1

### CODE REVIEW

**Review by brolal — APPROVED** [review]

**Review by justjinn — APPROVED** [review]

**Comment by gitr0n1n** [comment]
@IstoraMandiri no idea why the build is failing. Should hve been a simple PR. /fail 😆

**Comment by brolal** [comment]
please replace the video from my channel with this link https://www.youtube.com/watch?v=rbIm7vIApWo

**Comment by IstoraMandiri** [comment]
Weird, it looks like a bug with the latest version of gatsby https://github.com/gatsbyjs/gatsby/issues/34910

I'll try downgrading...

**Comment by IstoraMandiri** [comment]
Sorry this got automatically closed by the other commit message...

**Pull request merged**
