### PR TITLE
PoW Is Not Voting [opinion tag]

### PR DESCRIPTION
**Pull request by DonaldMcIntyre**
**If approved by editors, please post this article on Nov 18th** This is to follow my editorial calendar.

This is an article about the debate whether proof of work is a voting mechanism that we have debated with @IstoraMandiri and @phyro in several occasion (and it is a debate that exists widely in the industry) and it is worth an analysis because it lends itself to define some important concepts, explain how proof of work is true permissionlessness, and is also another angle of comparison with proof of stake. It is not really an article to "win" the debate, just to provide a long form analysis. 

Response articles by @IstoraMandiri and @phyro  are welcome!

Question, how do I post this in Chinese? (I have a translator who can do it)

### CODE REVIEW

**Comment by DonaldMcIntyre** [comment]
I got a 

❌ Deploy Preview for ethereumclassic failed.

Message. Anyone know how do I solve this?

cc @bobsummerwill ?

**Review by w1g0 — DISMISSED** [review]

**Review by TheCrowbill — DISMISSED** [review]
Good article

**Review by w1g0 — DISMISSED** [review]

**Comment by w1g0** [comment]
@DonaldMcIntyre, if there's no more changes you can merge this whenever you prefer.

**Review by TheCrowbill — APPROVED** [review]
aok

**Comment by DonaldMcIntyre** [comment]
@IstoraMandiri @w1g0 oh, sorry for entering changes after the approvals, I was not aware of that. I will try to make PRs with the product as finished as possible to minimize changes in the future. Thanks.

**Comment by w1g0** [comment]
> > 
> 
> No problem. If you want to make update and still see previews being generated, you can also convert a PR to a draft which will signal that we shouldn't approve it yet.
> 
> image

@DonaldMcIntyre, another way to go about this is to keep things in your fork until they're ready for publication and then make the pull request.

**Review by w1g0 — APPROVED** [review]

**Pull request merged**
