### PR TITLE
Add ZelCore to wallets as requested in issue #324

### PR DESCRIPTION
**Pull request by milesmanley**
Adds ZelCore to the ecosystem/wallets section as requested in issue #324

### CODE REVIEW

**Comment by hitchcott** [comment]
Looks fine, but can we have it in one section or the other as opposed to having duplicate entires.

Thanks.

**Comment by milesmanley** [comment]
@hitchcott - Hey, why should it only be in one section if there is support on both iOS and Android as well as all desktop platforms, Windows, Linux and macOS?

**Comment by hitchcott** [comment]
This is for consistency; right now there are other projects (e.g. Atomic wallet, Cononomi and JAXX) that have both mobile and desktop support but are only listed in mobile.

For now, please just put this in one or the other.

I will create a separate issue to create a third category for mobile and desktop.

**Comment by gitr0n1n** [comment]
We are revamping the website with a new content which includes a: /wallets page that includes with wallet in the "Software Wallets" section and this specific wallet.

See https://github.com/ethereumclassic/ethereumclassic.github.io/issues/328

**Pull request closed without merging**
