### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by TheEnthusiasticAs**

### CODE REVIEW

**Review by gitr0n1n — APPROVED** [review]
LGTM

**Review by w1g0 — COMMENTED** [review]
It looks like a typo on line 3 "hhttps://", it repeats on line 45 etc

**Comment by TheEnthusiasticAs** [comment]
> It looks like a typo on line 3 "hhttps://", it repeats on line 45 etc

yep, corrected. thx

**Review by w1g0 — APPROVED** [review]

**Review by gitr0n1n — APPROVED** [review]
typos...c'mon A.S.! 😆

**Comment by TheEnthusiasticAs** [comment]
> typos...c'mon A.S.! laughing

lol... happens )

**Pull request merged**
