### PR TITLE
Add Discord Cooperative to Chat Rooms on the website

### PR DESCRIPTION
**Pull request by w1g0**

### CODE REVIEW

**Comment by w1g0** [comment]
Preview shows Coop's Discord before Global, that wasn't the intent. Probably because C comes before G in the alphabet...

**Comment by IstoraMandiri** [comment]
> Preview shows Coop's Discord before Global, that wasn't the intent. Probably because C comes before G in the alphabet... Any suggestions/solutions?

Yes, they are alphabetically ordered.

**Comment by brolal** [comment]
I can't approve this, knowing the reasons behind Bob's "experiment"

**Comment by gitr0n1n** [comment]
> I can't approve this, knowing the reasons behind Bob's "experiment"

I'm of the same opinion as @brolal . I think this PR is a mistake and very premature given that discord is ~1 month old.

Rationale:

1. Creation:
Bob set this Discord server up in a rage after backlash from the contentious social battle regarding ECIP-1049 (three years). Given he was one of the proponents/champions in one of the most contentious ECIPs on the network (ECIP-1049) and he was a supporter of centralized treasury ECIP-1098,

2. Moderation
I find it very hard to recommend we recommend to novice Ethereum Classic entrants a centralize chatroom under his sole discretion. Bob doesn't have the moderation staff to handle sock puppets and all the other junk the primary discord moderators deal with on a daily basis. Bob has clearly stated intent to kick/ban people from this channel when contention rises. In the first month, his discord turned into a spam channel for questionable project ads. Is that where we want new users to land? A place where predatory projects can prey on them.

3. Attempted to list all social channel in 2019. It failed:
We already attempted to list every social channel in 2019 on the .org. The result went poorly with a bunch of social channels that didn't gain any traction and had maintainers that were absent. I believe one community channel turned into a bot spamming porn telegram chatroom. Go look at any of the old private team chatrooms. Impact of having two listed discords is dilution/fragmentation the community. Bob's article about bridging communication between Eastern and Western worlds highlights how this becomes a problem.

In my opinion, it's fine for ETC Coop to have a discord- I see no issue with it. We have seen this in the past by these teams: ETC Labs, IOHK (Mantis), Multi-Geth. I don't think it is appropriate to list it as a "Ethereum Classic" discord on the .org website.

4. Centralization concern under ETC Coop
The community has vocalized centralization concern of assets under ETC Coop after the other private teams withdrew engagement in the network. I don't think this PR would help is alleviating those centralization concerns. And this is definitely a project asset ETC Coop does not NEED to setup and spend resources on.

Note: it is much better economically to the network to have ETC Coop staff focused on running/maintaining functional public goods than moderating chatrooms with the money Grayscale allocated to this network. This money is intended to support the network and I can't imagine why Bob would think it was a good idea to budget resources toward a secondary chatroom.

These are my opinions and why I can't approved this PR.

**Review by gitr0n1n — COMMENTED** [review]
Edit: I think it makes sense to move this Discord to the "Development Chat" section of the social channels if you're going to approve this PR. After review of this seciton, I'm going to draft a PR cleaning up all these obscure social channels from 2019 that are stale or just spam as well.
https://github.com/ethereumclassic/ethereumclassic.github.io/pull/887

**Comment by gitr0n1n** [comment]
Source of 1.

> bobsummerwill — 08/15/2022
>@r0n1n You can take pretty much all of the credit for the creation for the creation of the new Discord server.   I was so thoroughly fed of listening to your bullshit, self congratulation, attacks and drama every fucking day (which you then auto-delete).
https://twitter.com/ETCCooperative/status/1559263188809437184

>As for the Twitter account, as I have said a hundred time already, IOHK own, Kevin has access, and all the recent posts you see after inaction since April (and very fallow times for months before that) are Kevin’s own initiative.   Thankfully we are seeing him pull at least a little out a seriously depressed period.   Coop never owned the Twitter account and Kevin was picking his own content even when employed by the Coop.  Ditto his modding here.

>There is no conspiracy here.  No Charles bogeyman.  He does not give a fuck about ETC or give it a second thought.  He won’t even reply to my repeated emails about the Twitter account.

>Stev likely popped his head back in in response to the new Discord and nothing more.  I have not spoken to him for months.

Appears this was Stev's doing (another 1049, 1097, 1098 proponent):  https://twitter.com/eth_classic/status/1559387795130556418
https://twitter.com/ETCCooperative/status/1559960891247906816

**Comment by gitr0n1n** [comment]
Speaking of Number 3 on my list. We should likely review/purge some of these social channels.

Look at the two Chinese telegram channels. Notice the pinned message in the top of the second chinese channel. 👀

**Comment by brolal** [comment]
> Edit: I think it makes sense to move this Discord to the "Development Chat" section of the social channels if you're going to approve this PR. After review of this seciton, I'm going to draft a PR cleaning up all these obscure social channels from 2019 that are stale or just spam as well. #887

**Comment by brolal** [comment]
or have on the clients page, yeah it makes sense

**Pull request closed without merging**
