### PR TITLE
Create 2021-12-16-community-call-with-bob-summerwill

### PR DESCRIPTION
**Pull request by IstoraMandiri**

### CODE REVIEW

**Review by brolal — CHANGES_REQUESTED** [review]
ETC Community Call with Bob Summerwill (guest)

Dear Friend:

We are pleased to invite you to participate in the upcoming Community Call to be held on Discord,  on Tuesday 21st December 2300 UTC, 2021.12.21. We will be joined by Bob Summerwill, Director of ETC Coop, for a festive chit chat and Q&A.

We would be delighted to have you present at this Call and hear you opinions and questions and share information about blockchain technology advancements, their impact on our businesses and daily lives. 

Best way to ask your question is by posting a message on Discord, or ask in person during the call. 

More information, including current questions, can be found here: https://github.com/ethereumclassic/community-calls/blob/main/20211221_005.md

We look forward to your presence at the Community Call

Screenshot from 2021-12-16 14-42-49

**Review by gitr0n1n — APPROVED** [review]
LGTM

**Review by w1g0 — DISMISSED** [review]
allso = also (line10)
Weely = Weekly (line15)

**Comment by IstoraMandiri** [comment]
Thanks @brolal , I have replaced the text with yours

**Review by brolal — APPROVED** [review]

**Review by brolal — APPROVED** [review]

**Review by brolal — APPROVED** [review]
Great!

**Review by brolal — APPROVED** [review]

**Review by IstoraMandiri — COMMENTED** [review]
Hmm, why can't this go through

**Review by brolal — APPROVED** [review]

**Pull request merged**
