### PR TITLE
add BSC-BUSD <=> ETC-USDT interoperability

### PR DESCRIPTION
**Pull request by HebeBlock**

### CODE REVIEW

**Comment by gitr0n1n** [comment]
@IstoraMandiri @brolal 

I want you guys to look at this one. So there is a bit of confusion with this product and its name. It appears as a USDT (Tether) bridged asset. But in reality it is a index of USD stablecoins, with the first stablecoin being BUSD, not USDT.

I personally feel it is a bid confusing to the end user, since they would not be receiving a USDT pegged asset in any fashion. I noticed confusion in the discord as well. That led me to ask the author in DM about the product and the naming confusion. This is how I was informed that the product's intention is to be an index of stablecoins, not a 1:1 peg.

I don't feel comfortable approving this one due to the obvious confusion this will cause end users. So I'll leave review to others.

**Review by gitr0n1n — COMMENTED** [review]
This product is an index fund of stablecoins bridged to ETC. Not a 1:1 peg of USDT to ETC. So the naming of this product is confusing on its surface.

Recommend: Properly naming the asset to the intent of the asset. Example: ETC-iUSD (index USD) or something of the nature.

Risk: End users think they are getting 1:1 pegged USDT but rather receive an index of a less secure stablecoin or a stablecoin that lacks the ability to redeem 1:1 like USDT does.

**Comment by HebeBlock** [comment]
gitr0n1n has also communicated with me about this issue privately, and it does cause some misunderstandings in the name, but I think it is enough to confirm the name of the website and bridge, because in the future we plan to aggregate multiple stablecoins into usdt on etc., Because it is a centralized service, we name it USDT, the full name should be ETC-USDT, not Tether as everyone understands.

**Review by brolal — APPROVED** [review]

**Comment by gitr0n1n** [comment]
> gitr0n1n has also communicated with me about this issue privately, and it does cause some misunderstandings in the name, but I think it is enough to confirm the name of the website and bridge, because in the future we plan to aggregate multiple stablecoins into usdt on etc., Because it is a centralized service, we name it USDT, the full name should be ETC-USDT, not Tether as everyone understands.

As discussed in DM- naming is USDT is confusing to the general public- You have stated you don't intend to change it and there is no going back.

My concern is listing something that appears to be USDT but is backed by other stablecoins. And that concern clearly has merit as we just watch UST implode.

So imagine ETC-USDT was backed 100% by UST....and users think they're buying USDT. See the clear problem there. If you aren't going to fix the naming- that is fine- but I can't approve this PR due to the misrepresentation to the general public in how you are naming the product. Other people are welcome to approve- but now the risks here. You will have inexperienced people thinking they're buying "Tether on ETC" because that is how the index is named. But they will not be buying a Tether peg.

I've clearly messaged my concerns. I'm not alone- the discord participants were all also confused- especially when you use the Tether logo on your swap product to indicate it is swapping to tether. It is a misrepresentation and it is easy to solve by appropriating naming your product and using a coin logo that does not deceive the end user.

**Comment by HebeBlock** [comment]
> > gitr0n1n has also communicated with me about this issue privately, and it does cause some misunderstandings in the name, but I think it is enough to confirm the name of the website and bridge, because in the future we plan to aggregate multiple stablecoins into usdt on etc., Because it is a centralized service, we name it USDT, the full name should be ETC-USDT, not Tether as everyone understands.
> 
> As discussed in DM- naming it USDT is confusing to the general public- You have stated you don't intend to change it and there is no going back.
> 
> My concern is listing something that appears to be USDT but is backed by other stablecoins. And that concern clearly has merit as we just watch UST implode.
> 
> So imagine ETC-USDT was backed 100% by UST....and users think they're buying USDT. See the clear problem there. If you aren't going to fix the naming- that is fine- but I can't approve this PR due to the misrepresentation to the general public in how you are naming the product. Other people are welcome to approve- but know the risks here. You will have inexperienced people thinking they're buying "Tether on ETC" because that is how the index is named. But they will not be buying a Tether peg.
> 
> I've clearly messaged my concerns. I'm not alone- the discord participants were all also confused- especially when you use the Tether logo on your swap product to indicate it is swapping to tether. It is a misrepresentation and it is easy to solve by appropriating naming your product and using a coin logo that does not deceive the end user. cc: @brolal @IstoraMandiri
> 
> image

I thought of a solution, we can change it to bsc-usdt->etc-usdt, yes, Binance has package usdt on bsc, so the problem will be solved

https://bscscan.com/token/0x55d398326f99059ff775485246999027b3197955

But the problem is that users still need to switch to Binance.

**Pull request closed without merging**
