### PR TITLE
News Updates

### PR DESCRIPTION
**Pull request by TheEnthusiasticAs**

### CODE REVIEW

**Comment by nargotik** [comment]
Nice 👍 Some more refresh and movement on page 👍

**Comment by nargotik** [comment]
There is a news that is repeated.
image

**Comment by TheEnthusiasticAs** [comment]
@nargotik thanks for the head up. I corrected and repulled

**Review by kimisan — APPROVED** [review]

**Review by gitr0n1n — APPROVED** [review]
LGTM.

**Pull request merged**
