### PR TITLE
Adding matrixport to the Apps section on the website

### PR DESCRIPTION
**Pull request by w1g0**
Please check https://github.com/ethereumclassic/ethereumclassic.github.io/issues/824 before reviewing.

### CODE REVIEW

**Comment by IstoraMandiri** [comment]
So this didnt work become for some reason the matrixport.png is just an empty file

**Comment by w1g0** [comment]
@IstoraMandiri unable to render code block

**Comment by w1g0** [comment]
I've put the /about in the team site but it links to the general website.

**Comment by w1g0** [comment]
@mp2023 this is the PR that needs to be approved before it can go live, you can watch a preview here https://deploy-preview-885--ethereumclassic.netlify.app/

**Comment by mp2023** [comment]
@w1g0 thanks

**Review by gitr0n1n — APPROVED** [review]

**Review by IstoraMandiri — APPROVED** [review]

**Pull request merged**
