### PR TITLE
Delete content - No POW, No Blockchain

### PR DESCRIPTION
**Pull request by DonaldMcIntyre**
I am deleting the post "If It's Not Proof of Work, Then It's Not a Blockchain" because some admins in this website have epistemological disorder so they see all networks that imitate the design of Nakamoto Consensus as "blockchains". I will post it on my personal blog, Etherplan, to promote myself because my traffic will increase from 30 unique users per day to 31 per day, so this will really make me thrive personally and financially.

### CODE REVIEW

**Review by brolal — APPROVED** [review]

**Comment by Neoclan45** [comment]
I woke up today I went in and it looks as though some one hacked me got on kucoin and set up so profits can be opened and taken on the 11th of the month every month unless the bot that was set up to automaticly invest did it there's a problem because someone is going through kucoin and it's going to open on the 11 of each month and they can take profits

**Comment by Neoclan45** [comment]
I also cannot connect to my wallet still ever since I accidently erased the first couple thousand blocks I mined it has messed up the file that connected me to my wallet that I have saved so I have no access to my money

**Comment by Neoclan45** [comment]
I can see my wallet on coinstats but I can only deposit to it not withdraw anything

**Comment by Neoclan45** [comment]
By the way I tried to connect to you on linked in awhile back so I'm excited to see you are on here mr mcintrye

**Comment by Neoclan45** [comment]
And the ppl that are imitating nakamoto block hains are not me those are ppl from China who hacked me I am nakamoto for real.

**Pull request merged**
