### PR TITLE
Update clients.en.yaml

### PR DESCRIPTION
**Pull request by gitr0n1n**
Add notes of intent to deprecate ETC support to Multi-Geth and OpenEthereum.

### CODE REVIEW

**Comment by gitr0n1n** [comment]
Great point with the disclaimer @zcstarr. There is a default disclaimer already, but perhaps an inline disclaimer noting the project is in its infancy.

**Comment by zcstarr** [comment]
For sure @gitr0n1n I just don't want us in a situation where a majority of miners switch to a project they think has the same level of support and trust as OpenEthereum.  It just really needs to be clear. I think there should be a Disclaimer next to the project given that the parent project was a tool used by the majority of the network. If there ever arose a security issue like there was with event-stream/flat-map bitcoin, where a dependency is compromised and one person is the maintainer of this software. ETC might be in a world of hurt.

For reference I'd like it if OpenETC grew to the level of support the other clients have or have enjoyed. That said I think for now for the sake of the people that tl;dr. We should have an *Experimental/Disclaimer* at minimum around the project.

**Comment by stevanlohja** [comment]
@gitr0n1n OpenETC was forked by an unknown user, unknown history, and unknown resource commitment to the project. From the first impression of the web page, it looks like OpenETC is being featured alongside Besu and Core-geth for production use, but given the unknowns, it does not seem OpenETC is in a state to be championed around for general production use.

**Comment by cryptoasuka** [comment]
> Additionally the support discord should not be the ethereum classic discord.

You could use the dedicated discord chatroom https://discord.gg/4PyGtp7 for receiving support of OpenETC

**Comment by gitr0n1n** [comment]
> For sure @gitr0n1n I just don't want us in a situation where a majority of miners switch to a project they think has the same level of support and trust as OpenEthereum. It just really needs to be clear. I think there should be a Disclaimer next to the project given that the parent project was a tool used by the majority of the network. If there ever arose a security issue like there was with event-stream/flat-map bitcoin, where a dependency is compromised and one person is the maintainer of this software. ETC might be in a world of hurt.
> 
> For reference I'd like it if OpenETC grew to the level of support the other clients have or have enjoyed. That said I think for now for the sake of the people that tl;dr. We should have an _Experimental/Disclaimer_ at minimum around the project.

I agree with you 100%, I suggest putting these thoughts into a PR to update the website to reflect this.

It would be great if Besu could get more adoption. Core-Geth seems to be absorbing a lot of the Multi-Geth users which is very welcomed given the recent attacks by the Multi-Geth maintainer.

Overall, I'm glad we are all acknowleding this attack vector and doing what we can to mitigate it. Great thoughts @zcstarr

**Comment by gitr0n1n** [comment]
For the record, the website is an open source project where anyone can submit PR's to adjust the website. I simply added OpenETC since it is effectively in the exact same devleopment path as OpenEthereum with only 1 release. And it was evolving news with a massive FUD campaign including paid for articles in the popular crypto publications. Both teams are a high risk due to uncertainly. It felt important for ParityEthereum users to know there was still a branch for them on ETC.

As we learned with OpenEthereum, they took the opportunity to attack ETC on July 20th 2020, the 4th anniversary of the DAO hard fork. And launched a marketing FUD campaign based off tht attack. So I think it is great to be cautious of the tools we are offerring our hashrate. So please feel free to append the website's copy to whatever you all feel would be best for the network's security. I'm happy to review and approve PR's.

Thank you all for your contributions and dialogue on the topic. It's great to have a paper trail of our actions outside of discord. Stay blessed.

**Comment by cryptoasuka** [comment]
> As we learned with OpenEthereum, they took the opportunity to attack ETC on July 20th 2020, the 4th anniversary of the DAO hard fork. And launched a marketing FUD campaign based off tht attack.

There is no doubt that they tried a social attack over 70% of the node operators on the anniversary of the DAO fork 😂 

OpenETC stands for continuous support upon the discontinued OpenEthereum support. With the growing contribution from the community, the project can grow for the network's strong bedrock, supporting thousands of DeFi and DApp developers building over Ethereum Classic.

**Comment by gitr0n1n** [comment]
These changes were addressed today.

It would be great if you could submit these type of changes in PR form moving forward. So we can review and merge the changes on the spot. Thanks a bunch. @stev and @zcstarr

**Comment by hitchcott** [comment]
See #531 531

**Comment by TheEnthusiasticAs** [comment]
My note to this:
Don't forget, based on the philosophy of this blockchain - open, permissionless, censorship-resistant - what the participants of this blockchain can do, is, to mark a contribution as "tested" or "untested".

Also, there is a note on the client site on on the website: 
"The links on this page are contributions by ETC participants and are not guaranteed to be safe; use them at your own risk! Please do your own research before using any of resources on this site."

**Pull request merged**
