### PR TITLE
Clients

### PR DESCRIPTION
**Pull request by TheEnthusiasticAs**
Update: 
Added an alternative link for " Ethereum Classic Client Upgrade Instructions", which is accessable from China, too
(Previous one: I added by mistake only one)

### CODE REVIEW

**Comment by gitr0n1n** [comment]
This appears to be a duplicate PR if I'm not mistaken?

**Comment by TheEnthusiasticAs** [comment]
One content is hosted on ETCCoop page and the another on hack.md. Should one will not be available, one can switch to another one.

**Comment by gitr0n1n** [comment]
> One content is hosted on ETCCoop (accessable for China viewers) page and the another on hack.md. Should one will not be available, one can switch to another one.

Okay, thats reasonable. I can see that logic. How about flipping the links though so the non-censored China link is the primary and the censored alternate link is the Hackmd. Sound good?

**Comment by TheEnthusiasticAs** [comment]
I put the hack.md link first, b/o it is the original source and one should be fair to the author.

**Comment by hitchcott** [comment]
Looks good to me.

@gitr0n1n @TheEnthusiasticAs please one of you two merge this if/when you are decided.

**Comment by TheEnthusiasticAs** [comment]
@gitr0n1n are you ok, if I merge it?

**Pull request merged**
