### PR TITLE
set ETCPlanets author

### PR DESCRIPTION
**Pull request by mr-arashmousavi**

### CODE REVIEW

**Review by w1g0 — COMMENTED** [review]
Author would be Milad?

   author: Milad
   authorLink: https://twitter.com/alien90th

**Comment by IstoraMandiri** [comment]
Sorry, but a twitter account is not acceptable as your author's website, which generates a "Team Site" check. 

Please remove `authorLink` or link to your actual homepage.

**Review by brolal — APPROVED** [review]

**Comment by w1g0** [comment]
@brolal, you drinking again? 😂

**Comment by w1g0** [comment]
@IstoraMandiri, does approving a closed PR reopen it? 🤔
This is very confusing.

**Pull request closed without merging**
