### PR TITLE
Ecosystem Update

### PR DESCRIPTION
**Pull request by gitr0n1n**
+Add Mining Pools
+Add Exchanges
-Remove Stale Mining Pools

### CODE REVIEW

**Review by hitchcott — APPROVED** [review]

**Comment by TheEnthusiasticAs** [comment]
@gitr0n1n, I checked the list and found at several websites the availability and activity of the Ethereum Classic token:
https://www.xnpool.com/
https://www.altilly.com/market/ETC_USDT
https://bitsonic.co.kr/front/en/exchange/etc-krw
https://app.btcmarkets.net/buy-sell?market=ETC-AUD
https://www.c2cx.com/trade/USDT_ETC
https://crex24.com/exchange/ETC-BTC
https://www.exx.com/tradeCoding/etc_usdt
https://okex.co.kr/kr/view/exchange?coin=ETC&market=BTC
https://www.probit.com/app/exchange/ETC-USDT
https://vcc.exchange/exchange/basic?currency=btc&coin=etc
https://bittorro.io/
Why were they deleted?

**Comment by gitr0n1n** [comment]
> @gitr0n1n, I checked the list and found at several websites the availability and activity of the Ethereum Classic token:
> https://www.xnpool.com/
> https://www.altilly.com/market/ETC_USDT
> https://bitsonic.co.kr/front/en/exchange/etc-krw
> https://app.btcmarkets.net/buy-sell?market=ETC-AUD
> https://www.c2cx.com/trade/USDT_ETC
> https://crex24.com/exchange/ETC-BTC
> https://www.exx.com/tradeCoding/etc_usdt
> https://okex.co.kr/kr/view/exchange?coin=ETC&market=BTC
> https://www.probit.com/app/exchange/ETC-USDT
> https://vcc.exchange/exchange/basic?currency=btc&coin=etc
> https://bittorro.io/
> Why were they deleted?

Deleted because they stopped supporting ETC or went out of business

**Comment by TheEnthusiasticAs** [comment]
> > @gitr0n1n, I checked the list and found at several websites the availability and activity of the Ethereum Classic token:
> > https://www.xnpool.com/
> > https://www.altilly.com/market/ETC_USDT
> > https://bitsonic.co.kr/front/en/exchange/etc-krw
> > https://app.btcmarkets.net/buy-sell?market=ETC-AUD
> > https://www.c2cx.com/trade/USDT_ETC
> > https://crex24.com/exchange/ETC-BTC
> > https://www.exx.com/tradeCoding/etc_usdt
> > https://okex.co.kr/kr/view/exchange?coin=ETC&market=BTC
> > https://www.probit.com/app/exchange/ETC-USDT
> > https://vcc.exchange/exchange/basic?currency=btc&coin=etc
> > https://bittorro.io/
> > Why were they deleted?
> 
> Deleted because they stopped supporting ETC or went out of business

Ok, but I checked them and ETC token is available/has active trades

**Comment by gitr0n1n** [comment]
> @gitr0n1n, I checked the list and found at several websites the availability and activity of the Ethereum Classic token:
> https://www.xnpool.com/ (added back)
> https://www.altilly.com/market/ETC_USDT (added back)
> https://bitsonic.co.kr/front/en/exchange/etc-krw (updated link)
> https://app.btcmarkets.net/buy-sell?market=ETC-AUD (updated link)
> https://www.c2cx.com/trade/USDT_ETC (updated link)
> https://crex24.com/exchange/ETC-BTC (added back)
> https://www.exx.com/tradeCoding/etc_usdt (added back)
> https://okex.co.kr/kr/view/exchange?coin=ETC&market=BTC (updated link)
> https://main.southxchange.com/Market/Book/ETC/USD  (updated link)
> https://vcc.exchange/exchange/basic?currency=btc&coin=etc (dead site)
> https://bittorro.io/ (no ETC support)


Okay i went through them and updated. @TheEnthusiasticAs nice catch on some of those, it was mainly broken links.

**Comment by TheEnthusiasticAs** [comment]
> > @gitr0n1n, I checked the list and found at several websites the availability and activity of the Ethereum Classic token:
> > https://www.xnpool.com/ (added back)
> > https://www.altilly.com/market/ETC_USDT (added back)
> > https://bitsonic.co.kr/front/en/exchange/etc-krw (updated link)
> > https://app.btcmarkets.net/buy-sell?market=ETC-AUD (updated link)
> > https://www.c2cx.com/trade/USDT_ETC (updated link)
> > https://crex24.com/exchange/ETC-BTC (added back)
> > https://www.exx.com/tradeCoding/etc_usdt (added back)
> > https://okex.co.kr/kr/view/exchange?coin=ETC&market=BTC (updated link)
> > https://main.southxchange.com/Market/Book/ETC/USD  (updated link)
> > https://vcc.exchange/exchange/basic?currency=btc&coin=etc (dead site)
> > https://bittorro.io/ (no ETC support)
> 
> Okay i went through them and updated. @TheEnthusiasticAs nice catch on some of those, it was mainly broken links.

Bittorro has support:
image
vcc.exchange:
the btc pairing works for me:
image

But take the USDT pairing pls:
https://vcc.exchange/exchange/basic?currency=usdt&coin=etc
image

Thanks for updating the others.

**Comment by gitr0n1n** [comment]
> > > @gitr0n1n, I checked the list and found at several websites the availability and activity of the Ethereum Classic token:
> > > https://www.xnpool.com/ (added back)
> > > https://www.altilly.com/market/ETC_USDT (added back)
> > > https://bitsonic.co.kr/front/en/exchange/etc-krw (updated link)
> > > https://app.btcmarkets.net/buy-sell?market=ETC-AUD (updated link)
> > > https://www.c2cx.com/trade/USDT_ETC (updated link)
> > > https://crex24.com/exchange/ETC-BTC (added back)
> > > https://www.exx.com/tradeCoding/etc_usdt (added back)
> > > https://okex.co.kr/kr/view/exchange?coin=ETC&market=BTC (updated link)
> > > https://main.southxchange.com/Market/Book/ETC/USD  (updated link)
> > > https://vcc.exchange/exchange/basic?currency=usdt&coin=etc (updated link)
> > > https://bittorro.io/ (added back)
> Thanks for updating the others.

Oh i see, on BitTorro i was typing in "ETC" and it wasn't showing up.

On VCC i still get the error that the site isn't live and its a cached page, but I see the price is accruate.

Added both back. Should be good now

**Review by TheEnthusiasticAs — APPROVED** [review]

**Pull request merged**
