### PR TITLE
News/red box Updates

### PR DESCRIPTION
**Pull request by TheEnthusiasticAs**

### CODE REVIEW

**Review by gitr0n1n — APPROVED** [review]
LGTM

**Comment by gitr0n1n** [comment]
@TheEnthusiasticAs can you add this into the PR:

https://www.youtube.com/watch?v=n_W-KfAH45s

**Comment by TheEnthusiasticAs** [comment]
add your request and some other from him @gitr0n1n

**Review by kimisan — APPROVED** [review]

**Review by kimisan — APPROVED** [review]

**Review by kimisan — APPROVED** [review]

**Comment by TheEnthusiasticAs** [comment]
@gitr0n1n need you help. There are errors again after I updated the red box

**Pull request merged**
