### PR TITLE
News Updates

### PR DESCRIPTION
**Pull request by TheEnthusiasticAs**

### CODE REVIEW

**Review by gitr0n1n — CHANGES_REQUESTED** [review]
Your URLs are duplicates

**Comment by TheEnthusiasticAs** [comment]
> Your URLs are duplicates

thank you, I updated it!

**Review by gitr0n1n — APPROVED** [review]
LGTM. Any chance you can update the CDC blog posts with accurate information as well? it doesn't appear anyone has submitted PR's to update the 9/11 post with the YT link or the 9/25 location. Thanks!

**Comment by TheEnthusiasticAs** [comment]
> LGTM. Any chance you can update the CDC blog posts with accurate information as well? it doesn't appear anyone has submitted PR's to update the 9/11 post with the YT link or the 9/25 location. Thanks!

Done. For 9/25 check please my comment in the corresponding issue "ETC Core Devs Call 13 & 14 nr: 362".

**Review by gitr0n1n — APPROVED** [review]

**Review by kimisan — APPROVED** [review]

**Pull request merged**
