### PR TITLE
Add Chinese community channel

### PR DESCRIPTION
**Pull request by HebeBlock**
If there are Chinese people who want to participate in the management, they can directly contact WeChat nanli777, and they will be given management rights.

### CODE REVIEW

**Comment by gitr0n1n** [comment]
This chatroom was removed due to it being a "project specific" chatroom. This is a hebeswap chatroom, not an Ethereum Classic chatroom.

```
      chat WeChat:
        __link: https://hebeswap.com/assets/nanli777.jpg
        name: WeChat (中文)
```

If we are going to add project specific chatrooms, we should be very clear about it. I imagine Hebeswap is heavily promoted in these chatroms due to the two people running the project (hebeswap staff). We don't see this from other teams in the ETC ecosystem and adding these without a clear disclaimer that they are hebeswap chatrooms would be a misrepresentation. No other team is trying to do this and they all have chatrooms.

**Comment by HebeBlock** [comment]
> This chatroom was removed due to it being a "project specific" chatroom. This is a hebeswap chatroom, not an Ethereum Classic chatroom.
> 
> ```
>       chat WeChat:
>         __link: https://hebeswap.com/assets/nanli777.jpg
>         name: WeChat (中文)
> ```
> 
> If we are going to add project specific chatrooms, we should be very clear about it. I imagine Hebeswap is heavily promoted in these chatroms due to the two people running the project (hebeswap staff). We don't see this from other teams in the ETC ecosystem and adding these without a clear disclaimer that they are hebeswap chatrooms would be a misrepresentation. No other team is trying to do this and they all have chatrooms.

He is not a chat room only for hebeswap, bob is in this chat room, you can refer to his opinions
nanli777 is not a hebeswap employee, he is just a fan of etc, he does a lot of things that are good for etc.
Participate in etc ama, rebuild etc Chinese community.

**Comment by zhj0829** [comment]
The Chinese community basically know how ridiculous the R0N1N is

**Comment by zhj0829** [comment]
It is not a wrong message that spreads, but some of the truth. The Hebe holder on ETC did not take you in your eyes because you didn't have technology!

**Comment by HebeBlock** [comment]
> This chatroom was removed due to it being a "project specific" chatroom. This is a hebeswap chatroom, not an Ethereum Classic chatroom.
> 
> ```
>       chat WeChat:
>         __link: https://hebeswap.com/assets/nanli777.jpg
>         name: WeChat (中文)
> ```
> 
> If we are going to add project specific chatrooms, we should be very clear about it. I imagine Hebeswap is heavily promoted in these chatroms due to the two people running the project (hebeswap staff). We don't see this from other teams in the ETC ecosystem and adding these without a clear disclaimer that they are hebeswap chatrooms would be a misrepresentation. No other team is trying to do this and they all have chatrooms.
> 
> Additionally, upon review I see content that is questionable and confirms my original thoughts that these chats are promotion of a specific product and not ETC chatrooms.
> 
> ```
>       telegram China:
>         __link: https://t.me/chinaetc
>         __icon: telegram
>         name: 中文
> ```
> 
> Example 1: When a user joins. The admin is promoting HebeSwap (This is a chatroom ran by hebeswap) image
> 
> Example 2: The owner of this chatroom is acting in bad faith and spreading misinformation about other ETC products to elevate their own product. image
> 
> image
> 
> Example 3: Redirecting chinese users to Hebeswap but saying it is ETC Swap
> 
> image
> 
> Example 4: These are mostly paid bot accounts to make it seem like its a "big chinese" community. Just scroll through the chat log. This was August 8th. Its the same group of guys. image
> 
> Solution: Create chinese channels that are legitimate and not hijacked by a single project with a narrative to sell.

etcswap.cc We deploy and use before your project goes live

in 2022/2/10

image

You only went online in April. Besides, it seemed that only hebe built the ecosystem at that time.

image

As for the question of nanli777 accusing you, you have also discussed in the discord。

**Comment by w1g0** [comment]
> It is not a wrong message that spreads, but some of the truth. The Hebe holder on ETC did not take you in your eyes because you didn't have technology!

This is off-topic, we would like an objective review to add an independant chatroom managed by the Chinese community.
Not some Hebe controlled channel, we didn't ask for some fanboys participating to criticize @gitr0n1n. If that's your purpose you're simply wasting my time, the person that is trying to fix the issue. I can understand your frustration but have also the required respect for the people that are trying to help.

**Comment by zhj0829** [comment]
Hebe压根没想跟你争什么东西，管好你自己得了，不要得寸进尺，老虎不发威，不要以为Hebe社区是病猫！ @gitr0n1n

**Comment by zhj0829** [comment]
> > 传播的不是错误信息，而是一些真相。ETC上的Hebe持有人没有把你放在眼里，因为你没有技术！
> 
> 这是题外话，我们想要一个客观的评论来添加一个由华人社区管理的独立聊天室。 不是一些Hebe控制的频道，我们没有要求一些粉丝参与批评@gitr0n1n. 如果这是您的目的，那么您只是在浪费我的时间，即试图解决问题的人。我可以理解您的沮丧，但也对试图提供帮助的人表示必要的尊重。

>ok

**Comment by HebeBlock** [comment]
> > It is not a wrong message that spreads, but some of the truth. The Hebe holder on ETC did not take you in your eyes because you didn't have technology!
> 
> This is off-topic, we would like an objective review to add an independant chatroom managed by the Chinese community. Not some Hebe controlled channel, we didn't ask for some fanboys participating to criticize @gitr0n1n. If that's your purpose you're simply wasting my time, the person that is trying to fix the issue. I can understand your frustration but have also the required respect for the people that are trying to help.

@bobsummerwill I think bob can comment, he is on wechat channel

image

**Comment by cc27149** [comment]
HEBE is just a project in the Ethereum Classic ecosystem, why would you want to block him? The variety of projects in Ethereum Classic is a good thing

**Comment by HebeBlock** [comment]
I am disappointed, no longer adding Chinese community links, and we will not help promote etc in the Chinese community in the future

**Comment by IstoraMandiri** [comment]
I approved #887 assuming that these were just dead or inactive channels.

Approving for now until we resolve the wording.

**Review by IstoraMandiri — APPROVED** [review]

**Review by Jamyye — APPROVED** [review]
Reviewed and approved.

**Pull request merged**
