### PR TITLE
Add Resource "Ethereum Classic Quickstart"

### PR DESCRIPTION
**Pull request by finxter**
Added an educational article from us about some beginner questions concerning ETH classic. It's a positive sentiment article because unlike many others in the ETH ecosystem, we believe in the decentralization and "code is law" philosophies of the ETH Classic community.

### CODE REVIEW

**Review by gitr0n1n — APPROVED** [review]

**Review by brolal — APPROVED** [review]

**Comment by IstoraMandiri** [comment]
While this is fine to add to the news section we should probably also add it to the list in the Basics section @finxter , feel free to make another PR

**Comment by w1g0** [comment]
Lol, what are these aggressive python cheat sheet popups on that blogsite? 😅

**Comment by finxter** [comment]
Thanks all for the great welcome! Love it already to hang around here. :) @w1g0 yeah, we should probably get rid of those given that it has nothing to do with Python... lol

**Comment by w1g0** [comment]
Hehe, welcome @finxter 🤗

**Comment by finxter** [comment]
> Hehe, welcome @finxter 🤗
Thanks, @w1g0 
By the way, I just fixed the popup issue you pointed out. Now, all Solidity and Blockchain-related content on our blog are popup-free (after caches refresh). You just improved the lives of hundreds of thousands of coders every year - not bad for a day's work! :) Thanks again!

**Pull request merged**
