### PR TITLE
Ecosystem Spotlight: Ethereum Classic DAO Part I

### PR DESCRIPTION
**Pull request by gitr0n1n**
This is part I of a running series that will explain what is Ethereum Classic DAO and its growing product suite (ETCswap, Griffin Finance, 4X Exchange...). It explains some of their products, the ECO token, several other things the team does, and leaves futures parts for guides of how to trade on ETCswap, use Griffin and 4X.

"ETC Ecosystem Spotlight: Ethereum Classic DAO Part I"

### CODE REVIEW

**Comment by DonaldMcIntyre** [comment]
I was going to write one like this! I would approved this one, but it seems to be empty.

**Comment by gitr0n1n** [comment]
Why would this be closed @DonaldMcIntyre , you literally just force merged this style of article.

**Comment by TheCrowbill** [comment]
Converted to draft due to placeholders in the content.

**Comment by DonaldMcIntyre** [comment]
This is a dishonest team that poses a risk to users of its dapps. I do not recommend anyone using their products nor publishing anything from this team to the Ethereum Classic community website.

**Comment by gitr0n1n** [comment]
> This is a dishonest team that poses a risk to users of its dapps. I do not recommend anyone using their products nor publishing anything from this team to the Ethereum Classic community website.

Can you expand on this opinion and show evidence of this "dishonest team that poses a risk to users of its dapps."? Or is this in relation to the push back you have received for violating the Github procedures in this repo?

Because if you did want to post this "dishonest team that poses a risk to users of its dapps." and it appeared to be false. One could consider that a violation of tort law as it pertains to trying to financial harm a company with false information in writing. And since we both reside in the United States, you being in Oklahoma, there could be consequences to those type of statements. 👍  I'll let you think about that for a bit.

**Comment by TheCrowbill** [comment]
Renamed for consistency with articles already merged to the website.

**Comment by gitr0n1n** [comment]
> Renamed for consistency with articles already merged to the website.

Thanks, I will write this up when appropriate since we are now allows to do product spotlight features and such due to Donald's crying.

**Comment by gitr0n1n** [comment]
Not a priority to me right now. Clearing the draft as it doesn't need to sit open atm.

**Pull request closed without merging**
