### PR TITLE
Update index.en.yaml

### PR DESCRIPTION
**Pull request by gitr0n1n**
Removed Core Paper from active dev teams. Applies faded css like other inactive teams.

Source: Sorpaas annoucement on twitter.

### CODE REVIEW

**Comment by gitr0n1n** [comment]
Regarding Sorpaas's "Core Paper" team moving to inactive status. He made an announcement this week:

"I have been supporting the development of Ethereum Classic since the early days. However, as of today, I have planned to deprecate my support of this particular blockchain." - Sorpaas

Source: his blog.

**Comment by gitr0n1n** [comment]
Per usual, more Sorpaas contension on any topic. Now he appears to want to be labeled as active, while annoucing intent to become inactive. Maybe he doesn't understand the designation. I'm not sure, but not vested enough to care to be honest. I was simply submitting the change based on his big social media marketing push about leaving ETC development.

From discord:
"sorpaas-don't-ping-me-at-night!06/13/2020
@r0n1n The PR is rather misleading to call it "inactive". Core Paper is now just similar to EF, IOHK and other teams -- we just don't provide any ETC-specific support any more."

I believe we should just keep the page factually accurate and mark him as inactive. If he decides to become an active developer again, it is extremely easy to mark him as active. The designation isn't too big of a deal.

**Comment by TheEnthusiasticAs** [comment]
Thx for putting the Core Paper to "active" status as discussed on discord.

**Comment by gitr0n1n** [comment]
@hitchcott i think this is failing due to that plugin cache bug. Can you solve that?

**Comment by hitchcott** [comment]
@gitr0n1n fixed that - there was a lil' YAML formatting issue

**Pull request merged**
