### PR TITLE
Remove swapika

### PR DESCRIPTION
**Pull request by ktechmidas**
Remove Swapika from exchanges, their website was created late last year:

Creation Date: 2022-11-17T17:05:20Z

With it showing a 403 until January: https://web.archive.org/web/20230110000317/https://swapika.com/

Their terms of use (https://swapika.com/terms-of-use) are a direct rip from ChangeNOW's terms of use (https://changenow.io/terms-of-use) including the address.

Bits to especially note in Swapika's terms of use:
> Newtonlaan 115, Utrecht, 3584 BH, Netherlands.

They also mentioned June 2021 until this was taken out earlier today.

> Please be aware that starting June 2021, Swapika works with a KYC provider called SumSub in order to prevent fraud.

This is still there, direct copy from ChangeNOW

> 15.3. Use of search queries comprising a direct domain name or the brand name such as (but not limited to) сhangenow, swapika.com, change now,

They have also been relentlessly spamming our forum (another crypto) with their exchange, despite removals, from a Turkish IP address.

### CODE REVIEW

**Comment by ktechmidas** [comment]
Here's another that's simply ripped changenow: https://fairmarketexchange.io/terms-of-use/

**Comment by jeroz1** [comment]
I started digging as well, because of a website mention (for yet another crypto). 

Personal conversations with a representative set off alarm bells. They claim that they "are in the process of re-registering the company to another address". While they never operated on the sole address listed on the website (copied from changenow). 

- Terms of service / Privacy statement nowhere mentions a real world entity that users deal with when using the swap exchange
- I cannot find anyone by the name the representative introduced himself as
- Through ICANN lookup, it is clear that the website itself was set up completely anonymously
- They copy-pasted a lot of changenow's website.

**Comment by ktechmidas** [comment]
@IstoraMandiri They're up now, but haven't been up long, this is my point as well as @jeroz1 's points

**Comment by TheCrowbill** [comment]
Does the `i18n\...\index.aa.yaml` file need to be edited directly or will simply editing `content\...\index.yaml` suffice?

**Comment by ktechmidas** [comment]
@IstoraMandiri Not really comparable since UniSwap is a DEX and Open Source, ChangeNOW is a centralized entity 

Further we do not know who Swapika are, there is no actual company behind it so no-one to complain to/zero accountability for the website.

The fact they ripped all their terms from ChangeNOW and refuse to reveal who they are (they listed ChangeNOW’s address, but there is no company by the name Swapika at that address)

They could disappear overnight if someone tried to convert a large amount and you’d never find them

**Comment by gitr0n1n** [comment]
Following this conversation.

Address concerns: Many companies use Registered Agents that register at an address they don't actually operate. This is extremely common.

Copying ToS: Many companies with a similar product will copy the industry leading products ToS when starting out as a CYA. This is because they likely have spent thousands on legal council to build these documents. It is odd/lazy they left the source company in the ToS as suggested in previous posts, but this does'nt make them a "scam" as its common on the internet to see clone products do so.

Regarding the allegations of scamming and such, is the product harming users? Did someone lose money in this? Does the product not work as designed? Does the product not support ETC? Can you provide some example about these topics that would indicate the product is harming users? If so, I'm happy to approve this PR. At this moment, I agree with @IstoraMandiri . This is a community ran website and projects are submitted by teams all over the world. Projects are easily removed if they appear dead (broken URLs/service), lack ETC support, or have known/reported issues with harming ETC users.

To look at this in a different lens, if this were your project and you copied some ToS document and used a popular Registered Agent, it would be unjust to remove the project you submitted to list here. You would feel that the anon community in ETC was gatekeeping your project from the community website listing.

Please keep this issue open while the submitters respond to the request for proof of customer loss of funds, a broken swapping product, or lack of ETC support. That proof would easily remove this product from the community site.

**Pull request closed without merging**
