### PR TITLE
Added in Alpha Wallet / Replace Trust Wallet in Porting Page

### PR DESCRIPTION
**Pull request by antsankov**
Trust Wallet has recently deprecated their Web3 Dapp Browser. Announcement here: https://community.trustwallet.com/t/trust-wallet-removed-dapp-browser-to-comply-with-apple-app-store-guidelines/30593

Alpha Wallet recently upgraded their ETC Dapp Browser support.

### CODE REVIEW

**Comment by TheEnthusiasticAs** [comment]
You are deleting the Trust Wallet, because they have no iOS version?

**Comment by antsankov** [comment]
That is a good point @TheEnthusiasticAs! - I only replaced it in Porting Section. This is because developers might recommend to users to download an app, but if the app only works for half the users (Android, not iOS) it can cause compatibility issues. 

AlphaWallet is good because it supports both equally! I also did not replace Trust Wallet in "Wallets" Section, only in "Porting"

**Comment by TheEnthusiasticAs** [comment]
go it. Thx.

**Comment by antsankov** [comment]
Good catch @gitr0n1n - removed the duplicate entry. Should be good to go!

**Pull request merged**
