### PR TITLE
Add SoyFinance to Apps

### PR DESCRIPTION
**Pull request by w1g0**

### CODE REVIEW

**Comment by w1g0** [comment]
Team site and test suite doesn't show 🤔

**Comment by w1g0** [comment]
I'll make a new PR for the last 2 commits

**Comment by w1g0** [comment]
This PR is integrated in https://github.com/ethereumclassic/ethereumclassic.github.io/pull/877

**Review by IstoraMandiri — APPROVED** [review]

**Comment by IstoraMandiri** [comment]
Not sure why the site not rendering teamSite, perhaps caching, let's see what happens when it merges.

If it doesn't work I'll open a new issue to figure out

**Comment by IstoraMandiri** [comment]
`teamSite` is still not showing up, might this be related to whitespace a la https://github.com/ethereumclassic/twitter-together/pull/38#issuecomment-1246032551

Will check later

**Review by brolal — APPROVED** [review]

**Pull request merged**
