### PR TITLE
Yu-Tam

### PR DESCRIPTION
**Pull request by yuriy0803**
warm Welcome

### CODE REVIEW

**Review by w1g0 — DISMISSED** [review]

**Comment by w1g0** [comment]
@yuriy0803, that ember.js frontend is looking mighty fine 👌
ps: passwort on the first page, could it be password?

**Review by IstoraMandiri — APPROVED** [review]

**Comment by IstoraMandiri** [comment]
I removed the primary label as there's only one miner

**Comment by yuriy0803** [comment]
@IstoraMandiri Yes unfortunately it is not a problem @w1g0  Thanks I will correct tonight

**Comment by w1g0** [comment]
> No need to make any more edits, I removed it for you.

He was referring to a typo on his website 😉

**Comment by IstoraMandiri** [comment]
Gotcha, btw @w1g0 you will need to re-approve this as I have made an edit, and the repo is now configured top require full reviews of edits due to prevent ninja edit thing.

**Comment by w1g0** [comment]
Ah, awesome 🙌

**Review by w1g0 — APPROVED** [review]

**Pull request merged**
