### PR TITLE
HebeSwap Review Part I

### PR DESCRIPTION
**Pull request by DonaldMcIntyre**
This is part I of a two part series that will explain what is HebeBlock and HebeSwap. It explains some of their products, the HEBE token, several other things the team does, and leaves for part II the guide of how to trade on HebeSwap.

"HebeSwap Review Part I"

EN.

CN coming soon. 

This post will be published on June 20th 2023. We have a 13 day lead.

### CODE REVIEW

**Comment by gitr0n1n** [comment]
@ethereumclassic/website you probably want to have a conversation about writing product specific content like this. Could be considered promotional to one product/product suite. The risk is it opens the doors for "reviews" of every product, something never done on this website.

I'll remain out of the discussion, since I would personally benefit from drafting and posting reviews about every protocol/product we have in the pipeline, but just noting this PR does open the flood gates to this type of new content to the website.

**Comment by TheCrowbill** [comment]
I agree with @gitr0n1n that this is a discussion we should have although I disagree with his reasoning the he should not be part of it. I think there is enough awareness of his involvement with a current project on ETC to alleviate any claims of a biased hidden agenda. In that light, I too am developing on ETC and have no plans to stay out of the discussion.

In my opinion, this website should definitively avoid promotion of or showing preference to any individual project. I would not welcome the predicted flood of product review articles, either.

Perhaps the issue I have is actually the idea of a product getting a review from ETC. In reading this particular article, it doesn't read like an opinionated product review but I anticipate that part two will. Real product reviews should delve into the pros and the cons of a particular implementation. They can and should be very critical of poorly engineered features. Are we prepared to stand behind such criticisms? Some media outlets such as Consumer Reports even subjectively score the products they review. That's but one step away from an "Editor's Choice" preferred recommendation. I am definitely not in favor of that.

A "Meet Your Developers" type of soft interview of an individual developer or a profile piece on a particular development team, even as a regular series like the ETC course, is a much more palatable format to me than that wherein an actual live product receives a critically opinionated review.

I think our articles about specific products should remain the walkthrough-style articles such as [this](https://ethereumclassic.org/blog/2022-12-21-using-ethereum-classic-with-metamask/) and {this](https://ethereumclassic.org/blog/2023-02-21-using-ethereum-classic-with-ledger-nano-s/). These articles are informative to the general audience and grant a measure of exposure and a tacit approval to the product and the developer without endorsement.

**Comment by DonaldMcIntyre** [comment]
Writing a review does not open the floodgates to anything and I write the reviews I thin are good for ETC in general. If anyone believes they have the right to get a review by me to post here, they are just silly and they can cry all they want. 

Why was not a MetaMask, Trust Wallet, MyCrypto, MyEtherwallet, DappNode, Antminer, Antpool, 2miners, and the Safe Multisig Wallet NOT a conflict before, but suddenly Hebe is? Answer: bias and true conflict of interest of the admin.

Like I said before, @gitr0n1n, I do not think you should even be an admin nor editor in ETC community assets. You are unstable and extremely biased in your commentary. 

This article is perfectly fine and I will keep writing and posting reviews of the products I think are good infrastructure and drivers of ETC's network effects. If the admins want to reject my posts, they are welcome to do so, so I will post them elsewhere.

All the products that I have covered here are extremely important for the ecosystem of ETC. Regardless, whether they are private startups or protocols that benefit financially specific teams.

**Comment by TheCrowbill** [comment]
> Why were not the MetaMask, Trust Wallet, Ledger, MyCrypto, MyEtherWallet, DappNode, Antminer, Antpool, iPollo, 2miners, and the Safe Multisig Wallet posts NOT a conflict before, but suddenly Hebe is? Answer: bias and true conflict of interest of the admin making this objection.

None of the articles to which you refer are "reviews". In fact, no article by any author is designated as a product review,  nor does any article have the word "review" in the title.

So none of those products you mentioned rose to the level of deserving a review,  but suddenly Hebe does? It appears as though, for whatever reason, something is a little different about the way Hebe is handled when compared to everything and everyone else.

**Comment by DonaldMcIntyre** [comment]
> None of the articles to which you refer are "reviews". In fact, no article by any author is designated as a product review, nor does any article have the word "review" in the title.
> 
> So none of those products you mentioned rose to the level of deserving a review, but suddenly Hebe does? It appears as though, for whatever reason, something is a little different about the way Hebe is handled when compared to everything and everyone else.

You are overthinking this. If the term "review" is what turns the whole article into suspected paid endorsement or an interested hidden motive behind the post, then that is ridiculous, and the title can be changed. Thinking of professional rating company kind of review is also ridiculous. And, if you have the anticipation that the second part was going to be an endorsement or shameless plug of HebeSwap, then you must have amnesia, because you suddenly forgot the more than 90 articles I have written in Etherplan supporting ETC and more than 100 articles I have written for this website that are only pro-ETC and have no bias toward any team. I don't care for any team in particular and it is sad that you have been conned by Ronin into this childish mindset. 

If you have a project and I think it is valuable for ETC I will cover it as well and the team.

In fact I asked Ronin first to do an interview so he would explain everything his team is doing and I was going to do "reviews" of his dapps as well, but it was not possible to set a date for the interview so I just continued with my editorial calendar that includes "reviewing" all relevant teams and products in ETC!!!!!!!!!!!!!!!!!!!!!!!

I can't believe I am wasting time in this idiotic conversation!!!!!!!!!!

And, @TheCrowbill ALL the other products that I covered ARE "reviews", that I didn't use that word was just that I had better titles and descriptions at the time. 

I have been writing product "reviews" for ten years for the most prominent tech companies and apps and dapps for 10 years. If I use the term "tutorial" or " "how to use X with ETC", or "Using X with ETC"....they are all reviews.

For your information, the "Hebe Swap Review Part II" is a step by step trade on HebeSwap to show the world how to use it just like 100% of the other tutorials I have made. "Part I" was going to be the intro of that tutorial, but it was so long that I decided to do it in two parts, like it has happened with all the other "part I and part II" post that I have done lately.

These posts take a lot of time in hours of research and production to do, it is a major frictional cost to have these non-objections and to handle them. Just let me know if the Hebe posts will go through or not so I just delete the PRs.

I can also change the title to remove the term "review". I can change it to something like "Decentralized Trading on ETC Using HebeSwap Part I" and "Decentralized Trading on ETC Using HebeSwap Part II".

I will review other swap dapps and products as well. There is no "preference" for Hebe, that is insulting.

**Comment by TheCrowbill** [comment]
> I can't believe I am wasting time in this idiotic conversation!!!!!!!!!!

I do not consider taking time to discuss and clarify the editorial policies of this important media publishing outlet to be a waste. I find it disturbing that you do not see any value in having this discussion. This is an important issue affecting how this website will be viewed by those outside the ETC community. You are reacting as though this were a personal attack on your work. It is not. Whether a particular piece of work is appropriate for a publishing outlet or not does not detract from the value of the work itself. 

> And, @TheCrowbill ALL the other products that I covered ARE "reviews", that I didn't use that word was just that I had better titles and descriptions at the time.

No, the other articles are not journalistic reviews which are defined as "a critical article or report, as in a periodical, on a book, play, recital, or the like; critique; evaluation." What you have presented in previous articles are basic user information and introductory usage instructions for a particular purpose. I cannot recall any article by you where there was a critique on HOW an application was implemented or that contained an opinion on the suitability of an application for a purpose, both of which are common parts of a review.

> For your information, the "Hebe Swap Review Part II" is a step by step sample trade on HebeSwap to show the world how to use it just like 100% of the other tutorials I have made. "Part I" was going to be the intro of that tutorial, but it was so long that I decided to do it in two parts, like it has happened with all the other "part I and part II" posts that I have done lately.

If part two is in fact a step-by-step guide,  then this entire article is not a review and should not be titled as such.
 
> I will review other swap dapps and products as well. There is no "preference" for Hebe, that is insulting.

I did not suggest there was a preference for Hebe. The fact is that I would have the same issues with and encourage a discussion on any articles which critically review a project no matter what it is or who made it. I don't think that this website is the proper venue for that type of content. You are welcome to disagree and we can debate the topic.

Speaking of insulting, I find your suggestion that my opinion is influenced by @gitr0n1n or anyone else to be demeaning and baseless. And as to Hebe, my earlier comment regarding the way things are handled when Hebe is involved was not suggesting you were paid to promote them. I meant exactly what I said.  When that group is involved, the normal way of doing things is not followed and an envelope is pushed. I have nothing against the Hebe Block team or their products. I was simply pointing out that fact.

**Comment by DonaldMcIntyre** [comment]
@TheCrowbill, yes this is a waste of time. You are a piece of work, Mr. CrowBill! Have you ever heard of mental cost? The cost of processing information in our limited minds? Well, we have to manage our mental time as best as possible, and dedicating it to this conversation is not going to accomplish this. I am deleting this post. I withdraw it from the ETC community website and withdraw authorization for it to be published in this outlet.

**Comment by DonaldMcIntyre** [comment]
> Personally I don't have a problem with substance of this article, as it does provide useful information to ETC researchers.
> 
> However I understand @TheCrowbill's contention that the word "review" may have certain connotations, and would typically mean a "critical appraisal" (or something like an amazon review). I think that neutrality should be maintained to avoid this potential (unintentional) interpretation.
> 
> So I think my only suggestion would be to changing the title, e.g. "Ecosystem Spotlight: Hebe", and add a short introduction that explains the purpose of the piece(s) - that it's not to be a comprehensive/critical review but to introduce people who aren't aware that Hebe as an important part of the ETC ecosystem.
> 
> CC @DonaldMcIntyre , I hope you don't mind me re-opening.
> 
> I think future such "spotlights" should be welcome content for the blog, as long as they don't claim to be "reviewing" in the sense that "this is good" or "this is bad".

No. You cannot re-open it and I prohibit its publication in this website.

**Pull request closed without merging**
