### PR TITLE
Adding ClassicDAO to dApps

### PR DESCRIPTION
**Pull request by StabeGa**

### CODE REVIEW

**Review by w1g0 — COMMENTED** [review]
Something seems to go wrong with the link to your logo @StabeGa
There's also only one check on the trust level is that correct?

**Review by gitr0n1n — APPROVED** [review]

**Review by gitr0n1n — CHANGES_REQUESTED** [review]
Fix logo link. Add links to increase Trust Score from 1 if possible.

**Review by brolal — APPROVED** [review]

**Review by w1g0 — APPROVED** [review]

**Review by w1g0 — APPROVED** [review]

**Comment by IstoraMandiri** [comment]
LGTM, but I would change the category to "Other" for now, I will add a DAOs category in near future.

**Comment by IstoraMandiri** [comment]
@StabeGa you can upload an image by going to https://github.com/StabeGa/ethereumclassic.github.io/tree/patch-1/content/services/apps/images and clikcing upload file (make sure it is title `classicdao.jpg`)

image

**Review by brolal — APPROVED** [review]

**Comment by StabeGa** [comment]
If you can add it there or something else I need to do
Contract Link - https://blockscout.com/etc/mainnet/token/0xfc84c3Dc9898E186aD4b85734100e951E3bcb68c
I am waiting for the code to be verified to then post the link here

**Comment by w1g0** [comment]
> If you can add it there or something else I need to do Contract Link - https://blockscout.com/etc/mainnet/token/0xfc84c3Dc9898E186aD4b85734100e951E3bcb68c I am waiting for the code to be verified to then post the link here

The idea is to edit the file you uploaded.

**Review by IstoraMandiri — APPROVED** [review]

**Pull request merged**
