### PR TITLE
Update: CDC 22 Call Results

### PR DESCRIPTION
**Pull request by gitr0n1n**
CDC 22 Call Results

### CODE REVIEW

**Comment by IstoraMandiri** [comment]
@gitr0n1n I suggest you make a new post rather than editing this one, so that it appears in people's RSS feeds etc.

Also, there will be a new video link as it will be moved to a different channel in a few minutes.

**Review by IstoraMandiri — APPROVED** [review]

**Comment by gitr0n1n** [comment]
> @gitr0n1n I suggest you make a new post rather than editing this one, so that it maintains a record, and it appears in people's RSS feeds etc.
> 
> Also, there will be a new video link as it will be moved to a different channel in a few minutes.

Good idea- done!

**Comment by IstoraMandiri** [comment]
By making a new post, I meant just adding one more item without editing the old one; there's no need to duplicate the content.

Either just revert to your original one with edited content (do not change the title or date, just update with conclusion), or add another completely separate post with just the conclusion, without copying all the original content, but linking back to he original.

**Comment by gitr0n1n** [comment]
> By making a new post, I meant just adding one more item without editing the old one; there's no need to duplicate the content.
> 
> Either just revert to your original one with edited content (do not change the date, just update with conclusion), or add another completely separate post with just the conclusion, without copying all the original content, but linking back to he original.
> 
> Easiest thing I can suggest is just make a new PR and add your conclusion, do not edit the date etc

Thanks- i reverted the old post and added a conclusion post with a later date. This should populate through the RSS feeds now. Appreciate the input.

**Review by IstoraMandiri — APPROVED** [review]

**Review by brolal — APPROVED** [review]

**Pull request merged**
