### PR TITLE
Update nl.yaml

### PR DESCRIPTION
**Pull request by w1g0**

### CODE REVIEW

**Comment by TheEnthusiasticAs** [comment]
Thanks @w1g0. FYI: This kind PR does not need reviewers as it does not change the English version, but one can still ask for reviews. You can just merge it. But it is always appropriate to have some to check for grammars and logic )

**Comment by hitchcott** [comment]
@TheEnthusiasticAs only repo maintainers can merge PRs I think

**Comment by hitchcott** [comment]
The build is failing due to the check links plugin, which is now removed. It should work in future.

**Comment by TheEnthusiasticAs** [comment]
@hitchcott yes, it is rational.

**Comment by w1g0** [comment]
> Thank you for the translation!

It is not finished yet but a work in progress ;)

**Comment by w1g0** [comment]
> Thanks @w1g0. FYI: This kind PR does not need reviewers as it does not change the English version, but one can still ask for reviews. You can just merge it. But it is always appropriate to have some to check for grammars and logic )

That's a great idea! I've started a conversation in the #Dutch channel for that particular reason.

**Pull request merged**
