### PR TITLE
Difference Between Network, Blockchain, Cryptocurrency

### PR DESCRIPTION
**Pull request by DonaldMcIntyre**
⚠️ ⚠️ **You may approve but please do not publish until 2022-11-29** (I can actually merge it on that date).

**The EN and ZH files are created with images, but we are awaiting the final translation fro the ZH file.**

This is the first article of a series of 7 that will end up explaining Core Geth, Hyperledger Besu, and Erigon on ETC.

### CODE REVIEW

**Comment by DonaldMcIntyre** [comment]
> @DonaldMcIntyre do you intend to make the English version live before the ZH version is ready, or will they both be published at the same time?
> 
> (And FYI I added the warning emojis to your original comment so this is not missed)

We usually publish both EN and ZH at the same time.

Thank you for the warning emojis!

**Comment by w1g0** [comment]
Coordination wise I suggest that @DonaldMcIntyre makes a review request once the final draft is completed.

**Comment by DonaldMcIntyre** [comment]
> Coordination wise I suggest that @DonaldMcIntyre makes a review request once the final draft is completed.

👍

**Review by gitr0n1n — DISMISSED** [review]
@IstoraMandiri this has a Chinese translated version. Is this approach compatible with the new internationalization code?

**Comment by DonaldMcIntyre** [comment]
> @DonaldMcIntyre in this case, we should not approve it yet as Chinese update will dismiss these reviews.
> 
> Please convert this to a Draft PR until it is ready is ready for approvals.
> 
> image
> 
> Thank you.

I am not finding the button to convert this PR into a draft.

**Review by gitr0n1n — APPROVED** [review]

**Review by w1g0 — APPROVED** [review]

**Comment by w1g0** [comment]
On line 99 it states that the ledger tracks a token called ETC, technically it's a coin.

**Comment by DonaldMcIntyre** [comment]
> On line 99 it states that the ledger tracks a token called ETC, technically it's a coin.

Yes, I am trying to use literary style so that I don't repeat "cryptocurrency" "currency" "money" "token" "unit" "monetary unit" or "coin" too much. The native currency of a blockchain may be called "native token" or "token" as well and non-native units like ERC-20 tokens may be called "tokens" or "coins" as well.

**Comment by w1g0** [comment]
> Yes, I am trying to use literary style so that I don't repeat "cryptocurrency" "currency" "money" "token" "unit" "monetary unit" or "coin" too much. The native currency of a blockchain may be called "native token" or "token" as well and non-native units like ERC-20 tokens may be called "tokens" or "coins" as well.

It may be used interchangeably but I tend to follow this definition:
https://www.ledger.com/academy/crypto/what-is-the-difference-between-coins-and-tokens

**Comment by DonaldMcIntyre** [comment]
> It may be used interchangeably but I tend to follow this definition:
> https://www.ledger.com/academy/crypto/what-is-the-difference-between-coins-and-tokens

That is a good article and definition. I call "coins" native tokens. I can change it in this article to coin. 

I may write an article about these definitions!!

**Pull request merged**
