### PR TITLE
Neutrality in Ecosystem Spotlight articles

### PR DESCRIPTION
**Pull request by IstoraMandiri**
This PR makes some edits to language and adds disclaimer to the Hebe article.

EDIT: There was also an older article for multichain that this also addresses.

It's separate from #1259 so that they can be merged and decided upon separately, but are not mutually exclusive.

CC https://github.com/ethereumclassic/ethereumclassic.github.io/pull/1252#pullrequestreview-1486607870
CC #1259
CC #1258 
CC #1252

### CODE REVIEW

**Comment by DonaldMcIntyre** [comment]
I prefer this article to be deleted, than castrated. 

You have fallen for Ronin's manipulation, Istora. How sad.

By the way, the Hebe post promises to be one of the most successful posts in the first 24 hour cycle of all the articles I have posted since November of 2023:

Screenshot 2023-06-19 at 7 16 29 PM

The most successful ones are MetaMask and Antminer!!!!!!!!!!!!!!

I WONDER WHY THOSE ARE NOT OBJECTED UPON???????????????

Answer: Because you were trapped in Ronin's manipulation and are yielding to his perversion. 

Again, as the author of this article please delete it before making these horrible modifications.

**Comment by DonaldMcIntyre** [comment]
This article is not controversial with other maintainers, it's only one clown, who shouldn't even be a maintainer, who is sabotaging the post and wasting all of our times only because he has competing products with the ones being covered. 

And if you are going to be legalistic, then this post should remain for the very legitimate reason that it was already approved by two admins.

**Comment by DonaldMcIntyre** [comment]
> > This article is not controversial with other maintainers, it's only one clown, who shouldn't even be a maintainer, who is sabotaging the post and wasting all of our times only because he has competing products with the ones being covered.
> > And if you are going to be legalistic, then this post should remain for the very legitimate reason that it was already approved by two admins.
> 
> I agree it should remain.
> 
> @gitr0n1n wanted to remove it in #1258 , which I don't think is the best option.
> 
> @TheCrowbill wants to add more disclaimers, which I think is good, but I don't think it's appropriate to call it promotional.
> 
> So I am trying to find a middle way here by making these minor neutrality tweaks, which I [suggested originally](https://github.com/ethereumclassic/ethereumclassic.github.io/pull/1238#issuecomment-1596100888).
> 
> So my opinion hasn't changed.

I agree to the edits of the text, but not to add a tag.

**Review by DonaldMcIntyre — DISMISSED** [review]

**Comment by gitr0n1n** [comment]
> I WONDER WHY THOSE ARE NOT OBJECTED UPON???????????????

Not everyone is following your actions every moment. I agree these are promotional posts by you and should be labeled as such. 👍

**Comment by gitr0n1n** [comment]
> 

Yes good call. the Multichain announcement should have promotional tag as well.

**Comment by gitr0n1n** [comment]
> I am not in favor of having promotional tag.
> 
> We should strive for neutrality while still providing useful information that is not promotional to people's attention.
> 
> Instead, the disclaimers about DYOR etc, and neutral language, as we have elsewhere, should suffice imo.

I think that multichain article drafted by ME...is exactly the reason to worry. And i think that is a PERFECT example to the rationale behind my ping. That bridge ended up being a very bad idea due to their design (unknown to the public). The poor design (centralization) was exposed in the FTX collapse and with the arrest of the CEO. At the time it was the most reputable bridge in the space- now I wouldn't touch it. I completely agree with you.

**Comment by gitr0n1n** [comment]
> I noticed that @gitr0n1n had previously added a similar article in the past: https://ethereumclassic.org/blog/2022-06-10-multichain-interoperability-to-ethereum-classic
> 
> I have updated this PR to match the new spotlight parameters and disclaimers.
> 
> Ronin, please feel free to edit the article with appropriate message, I have just added a link to your tweet for now.

Updated with tweet links and embedded text warnings. This is could not have been a better historic example of the conversation today regarding recent posts with the worst case scenario happening one year later. This is why conversation and discussion is so important to improve this website.

**Comment by DonaldMcIntyre** [comment]
> Thank you @DonaldMcIntyre
> 
> > but not to add a tag
> 
> Please could you clarify? Do you mean we should remove the `info:` disclaimer from this PR, or we should reject #1259 ?

Yes.

**Comment by DonaldMcIntyre** [comment]
> Another option here is to just have a disclaimer on every blog post, which I can do globally, which will also cover previous articles and make it so we don't need to be policing words so much including this post.
> 
> Will take a look at this and draft a PR.

This is a good idea.

**Review by TheCrowbill — APPROVED** [review]

**Review by TheCrowbill — APPROVED** [review]
These changes still need to be made.

**Review by DonaldMcIntyre — APPROVED** [review]

**Pull request merged**
