### PR TITLE
Wording in positioning landing page

### PR DESCRIPTION
**Pull request by sziv-agave**
This pull request changes the use of certain wording in our positioning. 

Line 33: Security may be equally important as decentralization (also, not sure if cryptocurrencies is the right concept here)
Line 35: I'd say ETC did not come to exist only to avoid censorship in ETH but for a some other matters which may be summarized with the Code is Law principle
Line 37: Added blockchains names and tickers to avoid reader's confusion in landing page, also highlight 'base layer' as there might be several smart contracts platforms in the future
Line 39: Minor 'it's' into 'its'

PS. First time adding a PR and open for any feedback.

### CODE REVIEW

**Review by gitr0n1n — DISMISSED** [review]
LGTM

**Review by IstoraMandiri — APPROVED** [review]

**Review by justjinn — COMMENTED** [review]
Changes seem ok, but maybe wait for the author to respond with a feed back.

**Comment by IstoraMandiri** [comment]
@sziv-agave Thanks for this PR and it looks good to me.

We recently merged a restructure which renamed the filename you are editing from `index.en.md` to `index.md`, which means there's a merge conflict on this PR.You didn't do anything wrong, it's just unfortunate timing as that other PR #961 was open for for a while.

Are you able to create a new pull request against the current master branch content; you can just copy and paste your changes into the newly renamed `content/index.md`?

Thanks!

**Review by IstoraMandiri — CHANGES_REQUESTED** [review]
Please re-create this PR against the new master branch, in `content/index.md`

**Review by TheCrowbill — CHANGES_REQUESTED** [review]
I have two issues with the Line 35 changes.

1. The proposed change is not correct English syntax.
2.  The proposed deletion "contract censorship on sister chain Ethereum" is not inaccurate. I suggest combining both concepts.

To correct both issues:

Existing in response to contract censorship on sister chain Ethereum and to uphold and preserve the principle of *Code is Law*, Ethereum Classic (ETC) has proven its ability to resist censorship against all odds and deliver the *original* Ethereum vision of *unstoppable* applications.

**Review by brolal — DISMISSED** [review]

**Review by TheCrowbill — APPROVED** [review]
Thank you for contributing, sziv-agave.

LGTM

**Comment by TheCrowbill** [comment]
Please don't forget to resolve the merging conflicts on your `sziv-agave:master` branch and resubmit the PR so it can be merged into the `ethereumclassic:master` branch. 

Thanks!

**Review by IstoraMandiri — APPROVED** [review]

**Pull request merged**
