### PR TITLE
Feature: Adds an Investor Resources page

### PR DESCRIPTION
**Pull request by antsankov**
Adds a new page which includes resources for those looking to invest in ETC. 
Also fixes some typos associated with the porting page.

### CODE REVIEW

**Comment by TheEnthusiasticAs** [comment]
Isn't it technically between 210 and 240mln?: 
"The Ethereum Classic Monetary Policy Explained

Etherplan explains the capped monetary policy of ETC, similar to Bitcoin. The total supply of ETC will converge on a number between 200m and 210m over the next century."

**Comment by antsankov** [comment]
@TheEnthusiasticAs  In the article https://etherplan.com/2020/02/25/the-ethereum-classic-monetary-policy-explained/10025/ he says it will be between 199m assuming minimal uncles blocks, and 211 assuming maximum uncle blocks. I'm not sure how 240m was calculated.

See screenshot: 

Screen Shot 2020-04-12 at 12 08 49 AM

**Comment by TheEnthusiasticAs** [comment]
My fail. I meaned up to 230mln as it is stated in the original documentation - the hard cap is at around 231mln.  https://ecips.ethereumclassic.org/ECIPs/ecip-1017

**Comment by TheEnthusiasticAs** [comment]
I will check etherplan's article and ping the author, if necessary.

All other lgtm.

**Comment by TheEnthusiasticAs** [comment]
I pinged the author and awaiting the answer.

**Pull request merged**
